# Generated by Django 5.2.4 on 2025-09-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('groups', models.ManyToManyField(related_name='admin_notifications', to='auth.group')),
            ],
        ),
    ]
