# Generated by Django 3.1.14 on 2022-07-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('groups', models.ManyToManyField(related_name='notifications', to='auth.Group')),
            ],
        ),
    ]
