# Generated by Django 3.2.25 on 2025-07-04 09:11

from django.db import migrations, models
import django.utils.timezone
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin_notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('groups', models.ManyToManyField(related_name='admin_notifications', to='auth.Group')),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
