FROM python:3.8.1-buster

ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt update -y
RUN apt install gettext -y

RUN pip install --upgrade pip
ADD ./requirements.txt ./requirements.dev.txt ./
RUN pip install -r requirements.dev.txt
