FROM python:3.8.1-buster

ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update --yes --quiet \
 && apt-get install --yes --quiet --no-install-recommends gettext tini \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements.dev.txt /
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r /requirements.dev.txt
