# Generated by Django 3.2.24 on 2024-03-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('rapidpro_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('quick_replies', models.JSONField(blank=True, null=True)),
                ('to', models.CharField(max_length=255)),
                ('from_field', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
