# Generated by Django 3.2.24 on 2024-03-23 12:52

from django.db import migrations, models
import django.db.models.deletion
import home.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('interactive', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractivePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('trigger_string', models.CharField(blank=True, help_text='Language short code will postfix after trigger string e.g string_en', max_length=255, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interactive.interactivechannel')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', home.mixins.PageUtilsMixin, home.mixins.TitleIconMixin),
        ),
    ]
