# Generated by Django 3.2.24 on 2024-03-28 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0003_interactivepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactivepage',
            name='button_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='interactivepage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interactive.interactivechannel'),
        ),
        migrations.AlterField(
            model_name='interactivepage',
            name='trigger_string',
            field=models.CharField(help_text='Language short code will postfix after trigger string e.g string_en', max_length=255),
        ),
    ]
