# Generated by Django 3.2.24 on 2024-05-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0004_auto_20240328_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactivepage',
            name='button_text',
        ),
        migrations.AlterField(
            model_name='interactivepage',
            name='trigger_string',
            field=models.CharField(max_length=255),
        ),
    ]
