# Generated by Django 3.2.24 on 2024-09-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0005_auto_20240506_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='rapidpro_message_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
