# Generated by Django 5.2.4 on 2026-09-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0006_auto_20240925_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='rapidpro_message_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
