translatable_strings = [
    'Username',
    'This field is required.',
    'survey',
    'poll',
    'Chat',
    'Cancel',
    'Send',
    'Reply',
    'Remove this comment?',
    'Remove',
    'Leave comment',
    'This comment has been removed.',
    'moderator',
    'Report',
    'sections',
    'articles',
    '%(counter)s of %(total)s questions',
    'Optional',
    'Select one',
    'Check all that apply',
    'Check if applies',
    'Comments',
    'Please log in or create your account',
    'New comments have been disabled for this page.',
    'Related Articles',
    'Log in',
    'Previous',
    'Page not found',
    'Sorry, this page could not be found.',
    'Internal server error',
    'Sorry, there seems to be an error. Please try again soon.',
    'Create your account',
    'quiz',
    'quizzes',
    'Your answer',
    'Next',
    'No limit',
    'Go to homepage',
    'Your results!',
    'Correct',
    'Incorrect',
    'Replay Quiz',
    'Correct answer',
    '1 result',
    'No search results were found for',
    'BACK',
    '© The Internet of Good Things',
    'Download',
    'Search the site...',
    'Log in / Create account',
    'You are leaving the <b>Internet of Good Things</b> to visit an external website and standard data charges by your network provider might apply',
    'Continue to external site',
    '4-digit PIN',
    'Old 4-digit PIN',
    'New 4-digit PIN',
    'Confirm new 4-digit PIN',
    'Hey, %(username)s',
    'Change Digital Pin',
    'Log out',
    'Personal Details',
    'Save changes',
    'Back',
    'section',
    'article',
    'Remember me',
    'You have signed out.',
    'Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters.',
    'You must type the same password each time.',
    'This password is too short. It must contain at least 4 characters.',
    'Please type your current password.',
    'Password successfully changed.',
    'Enter a valid date/time.',
    'Enter a valid date.',
    'Enter a valid URL.',
    'Enter a valid email address.',
    'Enter a valid integer.',
    'Ensure this value is greater than or equal to %(limit_value)s.',
    'Your comment',
    'Reset PIN',
    'Forgot PIN',
    'Your PIN has been changed successfully.',
    'I accept the Terms and Conditions.',
    '%(counter)s results',
    'Are you sure you want to log out?',
    'You have already completed this survey.',
    'Log in to participate',
    'You have read %(read)s out of %(total)s',
    'Profile',
    'This comment has been reported.',
    'Your browser does not support video playback.',
    'Your browser does not support audio playback.',
    "Don't display my username next to my comment",
    'Anonymous',
    'More',
    'Report this comment?',
    'It will be reviewed by the team and may be removed if it breaks our Platform Rules',
    'Display name',
    'Reported by %(comment_report_count)s user',
    'Reported by %(comment_report_count)s users',
    'Sorry, %(page_title)s is not available in %(language)s. If you want to keep browsing in %(language)s you can click below to return to the homepage.',
    'Username not available.',
    'Display name not available.',
    'Please complete the questions marked as required to continue',
    'You have already completed this quiz.',
    'You have already completed this poll.',
    'If you cannot view the above video, you can instead %(start_link)sdownload it%(end_link)s.',
    'If you cannot listen to the above audio, you can instead %(start_link)sdownload it%(end_link)s.',
    'You cannot submit when offline',
    'Search results for:',
    'Date must be in this (YYYY-MM-DD) format',
    'Datetime must be in this YYYY-MM-DDTHH:SS format',
    'Date must be in this (YYYY-MM-DD) format',
    'Datetime must be in this YYYY-MM-DDTHH:SS format',
    'The content you are trying to reach is not available. To see offline content click <a href="%(offline_content_index_page_url)s">here</a>',
    'Submit'
]