# Generated by Django 3.1.12 on 2021-06-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_section_show_progress_bar'),
        ('iogt_users', '0002_auto_20210624_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='viewed_articles',
            field=models.ManyToManyField(to='home.Article'),
        ),
    ]
