# Generated by Django 3.1.13 on 2021-11-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iogt_users', '0002_user_read_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='display name'),
        ),
    ]
