# Generated by Django 3.1.14 on 2022-01-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iogt_users', '0003_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_viewed_registration_survey',
            field=models.BooleanField(default=False),
        ),
    ]
