# Generated by Django 3.1.14 on 2022-01-20 08:13

from django.db import migrations


def _fill_has_viewed_registration_survey(apps, schema_editor):
    User = apps.get_model('iogt_users', 'User')
    User.objects.filter(has_filled_registration_survey=True).update(has_viewed_registration_survey=True)


def _unfill_has_viewed_registration_survey(apps, schema_editor):
    User = apps.get_model('iogt_users', 'User')
    User.objects.filter(has_filled_registration_survey=False).update(has_viewed_registration_survey=False)


class Migration(migrations.Migration):

    dependencies = [
        ('iogt_users', '0004_user_has_viewed_registration_survey'),
    ]

    operations = [
        migrations.RunPython(_fill_has_viewed_registration_survey, _unfill_has_viewed_registration_survey)
    ]
