# Generated by Django 3.1.14 on 2022-01-20 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iogt_users', '0004_user_has_viewed_registration_survey'),
    ]

    operations = [
    ]
