# Generated by Django 3.1.14 on 2023-03-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iogt_users', '0005_auto_20220120_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moyapay_username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='MoyaPay username'),
        ),
    ]
