# Generated by Django 5.2.4 on 2025-10-07 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iogt_users', '0007_user_date_of_birth_user_gender_user_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='Internal user ID (non-identifiable)')),
                ('deletion_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
