# Generated by Django 5.2.4 on 2025-12-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iogt_users', '0010_remove_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year',
        ),
    ]
