# Generated by Django 3.1.13 on 2026-09-25 16:40

from django.db.models import Count, F
from django.db.models.functions import Lower, Trim

from django.db import migrations
from django.db.models import Count, F
from django.db.models.functions import Lower, Trim


def make_duplicate_emails_unique(apps, schema_editor):
    User = apps.get_model("iogt_users", "User")

    normalized_email = Lower(Trim(F("email")))

    duplicate_emails = (
        User.objects
        .exclude(email__isnull=True)
        .exclude(email="")
        .annotate(normalized_email=normalized_email)
        .values("normalized_email")
        .annotate(email_count=Count("id"))
        .filter(email_count__gt=1)
        .values_list("normalized_email", flat=True)
    )

    duplicate_users = (
        User.objects
        .exclude(email__isnull=True)
        .exclude(email="")
        .annotate(normalized_email=normalized_email)
        .filter(normalized_email__in=duplicate_emails)
        .order_by("normalized_email", "id")
    )

    used_combinations = set()

    for is_superuser, is_staff, email in (
        duplicate_users
        .values_list(
            "is_superuser",
            "is_staff",
            "normalized_email",
        )
        .iterator(chunk_size=1000)
    ):
        used_combinations.add(
            (
                is_superuser,
                is_staff,
                email,
            )
        )

    users = duplicate_users.iterator(chunk_size=1000)

    processed_combinations = set()

    for user in users:
        email = user.normalized_email

        combination = (
            user.is_superuser,
            user.is_staff,
            email,
        )

        if combination not in processed_combinations:
            processed_combinations.add(combination)

            if user.email != email:
                user.email = email
                user.save(update_fields=["email"])

            continue

        local_part, domain = email.rsplit("@", 1)

        counter = 1

        while True:
            new_email = f"{local_part}+{counter:02d}@{domain}"

            new_combination = (
                user.is_superuser,
                user.is_staff,
                new_email,
            )

            if new_combination not in used_combinations:
                break

            counter += 1

        user.email = new_email
        user.save(update_fields=["email"])

        used_combinations.add(new_combination)
        processed_combinations.add(new_combination)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0061_article_notification_tags_section_notification_tags_and_more'),
        ('iogt_users', '0011_remove_user_gender_remove_user_location_and_more'),
    ]

    operations = [
        migrations.RunPython(
            make_duplicate_emails_unique,
            migrations.RunPython.noop,
        ),
    ]
