# Generated by Django 3.1.13 on 2022-09-07 15:40

from django.db import migrations


def make_duplicate_emails_unique(apps, schema_editor):
    User = apps.get_model("iogt_users", "User")

    users = (
        User.objects
        .exclude(email__isnull=True)
        .exclude(email="")
        .order_by("id")
    )

    used_emails = set()

    for user in users:
        email = user.email.strip().lower()

        # First occurrence stays unchanged
        if email not in used_emails:
            used_emails.add(email)

            if user.email != email:
                user.email = email
                user.save(update_fields=["email"])

            continue

        # Duplicate email
        local_part, domain = email.rsplit("@", 1)

        counter = 1

        while True:
            new_email = f"{local_part}+{counter:02d}@{domain}"

            if new_email not in used_emails:
                break

            counter += 1

        user.email = new_email
        user.save(update_fields=["email"])

        used_emails.add(new_email)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0061_article_notification_tags_section_notification_tags_and_more'),
        ('iogt_users', '0011_remove_user_gender_remove_user_location_and_more'),
    ]

    operations = [
        migrations.RunPython(
            make_duplicate_emails_unique,
            migrations.RunPython.noop,
        ),
    ]
