# Generated by Django 5.2.4 on 2026-10-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0061_article_notification_tags_section_notification_tags_and_more'),
        ('iogt_users', '0011_remove_user_gender_remove_user_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('is_staff', 'email'), name='iogt_users_user_unique_role_email'),
        ),
    ]
