# Generated by Django 5.2.4 on 2026-09-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iogt_users', '0011_remove_user_gender_remove_user_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='email address'),
        ),
    ]
