# Generated by Django 3.1.13 on 2026-09-25 16:40

from django.db import migrations
from django.db.models import Count, F
from django.db.models.functions import Lower, Trim

def make_duplicate_emails_unique(apps, schema_editor):
    User = apps.get_model("iogt_users", "User")

    normalized_email = Lower(Trim(F("email")))

    duplicate_emails = (
        User.objects
        .exclude(email__isnull=True)
        .exclude(email="")
        .annotate(normalized_email=normalized_email)
        .values("normalized_email")
        .annotate(email_count=Count("id"))
        .filter(email_count__gt=1)
        .values_list("normalized_email", flat=True)
    )

    users = (
        User.objects
        .exclude(email__isnull=True)
        .exclude(email="")
        .annotate(normalized_email=normalized_email)
        .filter(normalized_email__in=duplicate_emails)
        .order_by("normalized_email", "id")
    )

    used_emails = set()

    for user in users.iterator(chunk_size=1000):
        email = user.normalized_email

        # Protect the migration from malformed email values.
        if "@" not in email:
            continue

        if email not in used_emails:
            new_email = email
            used_emails.add(new_email)
        else:
            local_part, domain = email.rsplit("@", 1)

            counter = 1

            while True:
                new_email = f"{local_part}+{counter:02d}@{domain}"

                if new_email not in used_emails:
                    break

                counter += 1

            used_emails.add(new_email)

        if user.email != new_email:
            user.email = new_email
            user.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("home", "0061_article_notification_tags_section_notification_tags_and_more"),
        ("iogt_users", "0012_alter_user_email"),
    ]

    operations = [
        migrations.RunPython(
            make_duplicate_emails_unique,
            migrations.RunPython.noop,
        ),
    ]
