# Generated by Django 5.2.4 on 2026-09-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0061_article_notification_tags_section_notification_tags_and_more'),
        ('iogt_users', '0012_make_duplicate_emails_unique'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('is_superuser', 'is_staff', 'email'), name='iogt_users_user_unique_role_email'),
        ),
    ]
