# Generated by Django 3.2.25 on 2026-04-25 17:12

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbclandingpage',
            name='info',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
