# Generated by Django 3.2.25 on 2026-04-25 17:29

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0002_sbclandingpage_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbclandingpage',
            name='body',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.CharBlock(form_classname='title'))], blank=True, null=True, use_json_field=None),
        ),
    ]
