# Generated by Django 3.2.25 on 2026-04-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0003_sbclandingpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbclandingpage',
            name='body',
        ),
        migrations.AddField(
            model_name='sbclandingpage',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sbclandingpage',
            name='date',
            field=models.DateField(null=True, verbose_name='Post date'),
        ),
    ]
