# Generated by Django 3.2.25 on 2026-04-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0004_auto_20260425_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbclandingpage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sbclandingpage',
            name='date',
        ),
    ]
