# Generated by Django 3.2.25 on 2026-04-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0005_auto_20260425_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbclandingpage',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sbclandingpage',
            name='date',
            field=models.DateField(null=True, verbose_name='Post date'),
        ),
    ]
