# Generated by Django 3.2.25 on 2026-04-25 18:05

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0006_auto_20260425_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbclandingpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock())], blank=True, null=True, use_json_field=None),
        ),
        migrations.AlterField(
            model_name='sbclandingpage',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sbclandingpage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Post date'),
        ),
    ]
