# Generated by Django 3.2.25 on 2026-04-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('sbc', '0007_auto_20260425_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbclandingpage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sbclandingpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='sbclandingpage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sbclandingpage',
            name='info',
        ),
        migrations.AddField(
            model_name='sbclandingpage',
            name='hero_bk_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='sbclandingpage',
            name='hero_cta_label',
            field=models.CharField(default='Red SBC LAC – Plataforma de Aprendizaje y Conocimiento', max_length=255),
        ),
        migrations.AddField(
            model_name='sbclandingpage',
            name='hero_cta_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sbclandingpage',
            name='hero_description',
            field=models.TextField(default='Instituciones académicas de ocho países de América Latina y el Caribe\xa0unen esfuerzos para abordar temas críticos para la infancia y adolescencia.'),
        ),
        migrations.AddField(
            model_name='sbclandingpage',
            name='hero_title',
            field=models.CharField(default='Red SBC LAC – Plataforma de Aprendizaje y Conocimiento', max_length=255),
        ),
    ]
