# Generated by Django 3.2.25 on 2026-04-25 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('sbc', '0008_auto_20260425_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbclandingpage',
            name='about_description_1',
            field=models.TextField(default='América Latina y el Caribe enfrentan desafíos complejos en torno a las infancias y sus derechos, por ejemplo: dos de cada tres niños, niñas y adolescentes, de edades comprendidas entre 1 y 14 años, en la región experimentan disciplina violenta en el hogar.'),
        ),
        migrations.AddField(
            model_name='sbclandingpage',
            name='about_description_2',
            field=models.TextField(default='Esta alianza es una plataforma estratégica de reflexión y acción, fruto de un proceso de colaboración sostenida entre el sector académico, sociedad civil y UNICEF a favor de los derechos de la niñez.'),
        ),
        migrations.AddField(
            model_name='sbclandingpage',
            name='about_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='sbclandingpage',
            name='about_title',
            field=models.CharField(default='Acerca de la Alianza UNICEF - Uninorte', max_length=255),
        ),
        migrations.AlterField(
            model_name='sbclandingpage',
            name='hero_cta_label',
            field=models.CharField(blank=True, default='Red SBC LAC – Plataforma de Aprendizaje y Conocimiento', max_length=255, null=True),
        ),
    ]
