# Generated by Django 3.2.25 on 2026-04-26 00:13

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0011_sbcfooter_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbcheader',
            name='links',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(label='Label')), ('url', wagtail.blocks.CharBlock(label='Link'))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
