# Generated by Django 3.2.25 on 2026-04-26 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0012_sbcheader_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sbcfooter',
            options={'verbose_name': 'SBC Footer', 'verbose_name_plural': 'SBC Footers'},
        ),
        migrations.AlterModelOptions(
            name='sbcheader',
            options={'verbose_name': 'SBC Header', 'verbose_name_plural': 'SBC Headers'},
        ),
    ]
