# Generated by Django 3.2.25 on 2026-04-26 01:04

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('sbc', '0013_auto_20260426_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbclandingpage',
            name='resources_cta_label',
            field=models.CharField(blank=True, default='Ver mas recursos', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sbclandingpage',
            name='resources_cta_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sbclandingpage',
            name='resources_list',
            field=wagtail.fields.StreamField([('resources_list', wagtail.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('sbc.SBCResource'), heading='Select Resources', template='sbc/blocks/resource_grid.html'))], blank=True, null=True, use_json_field=True),
        ),
        migrations.CreateModel(
            name='SBCResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Author')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='File (PDF, etc.)')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Thumbnail')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Biblioteca de Recursos',
            },
        ),
    ]
