# Generated by Django 3.2.25 on 2026-04-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0014_auto_20260426_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sbcresource',
            options={'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterField(
            model_name='sbclandingpage',
            name='hero_cta_label',
            field=models.CharField(blank=True, default='Ver recursos', max_length=255, null=True),
        ),
    ]
