# Generated by Django 3.2.25 on 2026-04-26 15:07

import django.core.validators
from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0015_auto_20260426_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbcfooter',
            name='unicef_link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='sbcfooter',
            name='university_link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='sbcheader',
            name='links',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(label='Label')), ('url', wagtail.blocks.CharBlock(label='Link', validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='sbclandingpage',
            name='hero_cta_link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='sbclandingpage',
            name='resources_cta_link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='sbcresource',
            name='link',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Link'),
        ),
    ]
