# Generated by Django 3.2.25 on 2026-04-26 15:37

import django.core.validators
from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0018_auto_20260426_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbcfooter',
            name='links',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(label='Label')), ('url', wagtail.blocks.CharBlock(help_text='Link must begin with http:// or https://', label='Link'))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='sbcheader',
            name='links',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(label='Label')), ('url', wagtail.blocks.CharBlock(help_text='External links must begin with http:// or https://', label='Link'))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='sbclandingpage',
            name='hero_cta_link',
            field=models.URLField(blank=True, help_text='Link must begin with http:// or https://', null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='sbclandingpage',
            name='resources_cta_link',
            field=models.URLField(blank=True, help_text='Link must begin with http:// or https://', null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
