# Generated by Django 3.2.25 on 2026-04-26 15:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('sbc', '0020_auto_20260426_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbcfooter',
            name='links',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(label='Label')), ('url', wagtail.blocks.PageChooserBlock(label='Link to Page', required=False))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='sbcfooter',
            name='unicef_link',
            field=models.URLField(blank=True, help_text='Link must begin with http:// or https://', null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='sbcfooter',
            name='university_link',
            field=models.URLField(blank=True, help_text='Link must begin with http:// or https://', null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='sbcheader',
            name='links',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(label='Label')), ('url', wagtail.blocks.PageChooserBlock(label='Link to Page', required=False))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='sbclandingpage',
            name='hero_cta_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Hero CTA Page'),
        ),
        migrations.AlterField(
            model_name='sbclandingpage',
            name='resources_cta_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Resources CTA Page'),
        ),
        migrations.AlterField(
            model_name='sbcresource',
            name='link',
            field=models.URLField(blank=True, help_text='External links must begin with http:// or https://', verbose_name='Link'),
        ),
    ]
