# Generated by Django 3.2.25 on 2026-04-26 16:17

from django.db import migrations
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0023_auto_20260426_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbclandingpage',
            name='resources_list',
            field=wagtail.fields.StreamField([('resource', wagtail.snippets.blocks.SnippetChooserBlock('sbc.SBCResource'))], blank=True, null=True, use_json_field=True),
        ),
    ]
