# Generated by Django 3.2.25 on 2026-04-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0024_alter_sbclandingpage_resources_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbclandingpage',
            name='resources_title',
            field=models.CharField(blank=True, default='Recursos Destacados', max_length=255, null=True),
        ),
    ]
