# Generated by Django 3.2.25 on 2026-04-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0026_sbcresourcespage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbcresourcespage',
            name='resources_description',
            field=models.TextField(default='América Latina y el Caribe enfrentan desafíos complejos en torno a las infancias y sus derechos, por ejemplo: dos de cada tres niños, niñas y adolescentes, de edades comprendidas entre 1 y 14 años, en la región experimentan disciplina violenta en el hogar.'),
        ),
        migrations.AddField(
            model_name='sbcresourcespage',
            name='resources_title',
            field=models.CharField(default='Acerca de la Alianza UNICEF - Uninorte', max_length=255),
        ),
    ]
