# Generated by Django 3.2.25 on 2026-04-27 14:46

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('sbc', '0027_auto_20260426_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBCAlliancePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('alliance_title', models.CharField(default='Sobre la Alianza', max_length=255)),
                ('alliance_description', wagtail.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='sbcresourcespage',
            name='resources_description',
            field=models.TextField(default='Mapeo de universidades con trabajo, cursos y recursos en infancias y SBC'),
        ),
        migrations.AlterField(
            model_name='sbcresourcespage',
            name='resources_title',
            field=models.CharField(default='Recursos', max_length=255),
        ),
    ]
