# Generated by Django 3.2.25 on 2026-04-27 14:58

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0028_auto_20260427_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbcalliancepage',
            name='alliance_description',
            field=wagtail.fields.RichTextField(default='<p>La alianza entre UNICEF LACRO y la Fundación Universidad del Norte (Uninorte) tiene como propósito fortalecer las capacidades en Cambio Social y de Comportamiento (SBC) en América Latina y el Caribe, a través de la articulación entre academia, sector público y organizaciones sociales.</p><p>Esta colaboración impulsa la creación y consolidación de una Red Académica Regional, orientada a generar conocimiento, formar talento y promover la implementación de estrategias de SBC contextualizadas a las realidades culturales y sociales de la región.</p>'),
        ),
    ]
