# Generated by Django 3.2.25 on 2026-04-27 15:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('sbc', '0029_alter_sbcalliancepage_alliance_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbcalliancepage',
            name='alliance_lines_list',
            field=wagtail.fields.StreamField([('line', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Title', max_length=255)), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link']))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='sbcalliancepage',
            name='alliance_lines_title',
            field=models.CharField(default='Líneas de Trabajo', max_length=255),
        ),
        migrations.AddField(
            model_name='sbcalliancepage',
            name='alliance_purpose_description',
            field=wagtail.fields.RichTextField(default='<p>Contribuir al fortalecimiento de capacidades técnicas, la generación de evidencia y la articulación regional en SBC, mediante la creación de una red académica sostenible que conecte universidades, gobiernos, UNICEF y otros actores clave. </p>'),
        ),
        migrations.AddField(
            model_name='sbcalliancepage',
            name='alliance_purpose_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='sbcalliancepage',
            name='alliance_purpose_title',
            field=models.CharField(default='Propósito General', max_length=255),
        ),
        migrations.AlterField(
            model_name='sbcalliancepage',
            name='alliance_description',
            field=wagtail.fields.RichTextField(default='<p>La alianza entre UNICEF LACRO y la Fundación Universidad del Norte (Uninorte) tiene como propósito fortalecer las capacidades en Cambio Social y de Comportamiento (SBC) en América Latina y el Caribe, a través de la articulación entre academia, sector público y organizaciones sociales.</p><br><br><p>Esta colaboración impulsa la creación y consolidación de una Red Académica Regional, orientada a generar conocimiento, formar talento y promover la implementación de estrategias de SBC contextualizadas a las realidades culturales y sociales de la región.</p>'),
        ),
    ]
