# Generated by Django 3.2.25 on 2026-04-27 15:35

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0030_auto_20260427_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbcalliancepage',
            name='alliance_achievements_list',
            field=wagtail.fields.StreamField([('achievement', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255)), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link']))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='sbcalliancepage',
            name='alliance_achievements_title',
            field=models.CharField(default='Principales Logros\xa0', max_length=255),
        ),
        migrations.AlterField(
            model_name='sbcalliancepage',
            name='alliance_lines_list',
            field=wagtail.fields.StreamField([('line', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255)), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link']))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
