# Generated by Django 3.2.25 on 2026-04-27 15:50

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0031_auto_20260427_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbcalliancepage',
            name='alliance_gallery_description',
            field=wagtail.fields.RichTextField(default='<p>Algunas fotos relacionadas al proyecto</p>'),
        ),
        migrations.AddField(
            model_name='sbcalliancepage',
            name='alliance_gallery_list',
            field=wagtail.fields.StreamField([('gallery', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))], icon='image'))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='sbcalliancepage',
            name='alliance_gallery_title',
            field=models.CharField(default='Galeria', max_length=255),
        ),
        migrations.AddField(
            model_name='sbcalliancepage',
            name='alliance_timeline_description',
            field=wagtail.fields.RichTextField(default='<p>ALIANZA UNICEF & UNINORTE (2022–2026)</p>'),
        ),
        migrations.AddField(
            model_name='sbcalliancepage',
            name='alliance_timeline_list',
            field=wagtail.fields.StreamField([('timeline', wagtail.blocks.StructBlock([('year', wagtail.blocks.CharBlock(max_length=255)), ('title', wagtail.blocks.CharBlock(max_length=255)), ('subtitle', wagtail.blocks.CharBlock(max_length=255)), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul', 'ol']))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='sbcalliancepage',
            name='alliance_timeline_title',
            field=models.CharField(default='Linea de tiempo', max_length=255),
        ),
    ]
