# Generated by Django 3.2.25 on 2026-04-27 15:50

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0032_auto_20260427_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbcalliancepage',
            name='alliance_gallery_list',
            field=wagtail.fields.StreamField([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))], blank=True, null=True, use_json_field=True),
        ),
    ]
