# Generated by Django 3.2.25 on 2026-04-27 15:51

from django.db import migrations
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0033_alter_sbcalliancepage_alliance_gallery_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbcalliancepage',
            name='alliance_gallery_list',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True, use_json_field=True),
        ),
    ]
