# Generated by Django 3.2.25 on 2026-04-27 15:58

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0034_alter_sbcalliancepage_alliance_gallery_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbcalliancepage',
            name='alliance_timeline_list',
            field=wagtail.fields.StreamField([('timeline', wagtail.blocks.StructBlock([('year', wagtail.blocks.CharBlock(max_length=255)), ('title', wagtail.blocks.CharBlock(max_length=255)), ('subtitle', wagtail.blocks.CharBlock(blank=True, max_length=255, null=True)), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul', 'ol']))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
