# Generated by Django 3.2.25 on 2026-04-27 16:05

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0036_alter_sbcalliancepage_alliance_timeline_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbcalliancepage',
            name='alliance_achievements_list',
            field=wagtail.fields.StreamField([('achievement', wagtail.blocks.StructBlock([('description', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link']))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
