# Generated by Django 3.2.25 on 2026-04-29 17:22

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('sbc', '0037_alter_sbcalliancepage_alliance_achievements_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBCNetworkPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('network_title', models.CharField(default='Red Académica de Intercambio y Aprendizaje sobre Cambio Social y de Comportamiento (SBC)', max_length=255)),
                ('network_description', wagtail.fields.RichTextField(default='<p>La Red Académica de Intercambio y Aprendizaje sobre Cambio Social y de Comportamiento (SBC) en favor de la infancia en América Latina y el Caribe es una iniciativa impulsada por UNICEF LACRO en alianza con la Universidad del Norte (UNINORTE), orientada a fortalecer la articulación entre la academia, organismos internacionales, gobiernos y sociedad civil para promover transformaciones sociales sostenibles en la región.</p><br><br><p>La Red surge como resultado de un proceso iniciado en 2023, que ha integrado formación, generación de conocimiento y diálogo regional en torno al enfoque de Cambio Social y de Comportamiento, permitiendo consolidar una base académica y técnica sólida para su desarrollo.</p><br><br><p>La Red tiene como propósito consolidar una plataforma regional de aprendizaje, investigación e innovación, que contribuya al fortalecimiento de capacidades técnicas, la producción de evidencia y la implementación de estrategias de cambio social y de comportamiento orientadas a mejorar las condiciones de vida de niños, niñas y adolescentes en América Latina y el Caribe. </p>')),
                ('network_strategies_title', models.CharField(default='¿Qué hacemos?', max_length=255)),
                ('network_strategies_description', wagtail.fields.RichTextField(default='<p>La Red articula sus acciones en torno a seis líneas estratégicas:</p>')),
                ('network_strategies_list', wagtail.fields.StreamField([('strategy', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255)), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link']))]))], blank=True, null=True, use_json_field=True)),
                ('network_focus_title', models.CharField(default='Un enfoque regional, colaborativo y centrado en la niñez', max_length=255)),
                ('network_focus_body', wagtail.fields.RichTextField(default='\n            <p>La Red reúne universidades y actores académicos de América Latina y el Caribe, promoviendo un enfoque:</p>\n            <br><br>\n            <ul>\n                <li><b>Colaborativo</b>, basado en el diálogo de saberes</li>\n                <li><b>Contextualizado</b>, adaptado a las realidades culturales de la región</li>\n                <li><b>Interdisciplinario</b>, integrando diversas áreas del conocimiento</li>\n                <li><b>Centrado en derechos</b>, con énfasis en la niñez y la equidad</li>\n            </ul>\n            <br><br>\n            <p>Entre sus áreas prioritarias se encuentran la inmunización, la nutrición, la  educación, la protección contra la violencia, la salud mental, la  inclusión social y la acción climática.</p>\n        ')),
                ('network_focus_download_description', wagtail.fields.RichTextField(default='<p><i>Haz click aqui debajo para descargar la <b>“Nota Conceptual - Red Académica de Centros de Aprendizaje”</b></i></p>', max_length=255)),
                ('network_focus_download_link', models.URLField(blank=True, help_text='External links must begin with http:// or https://', verbose_name='Link')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SBCUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('link', models.URLField(blank=True, help_text='External links must begin with http:// or https://', verbose_name='Link')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Thumbnail')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
    ]
