# Generated by Django 3.2.25 on 2026-05-06 15:10

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('sbc', '0038_sbcnetworkpage_sbcuniversity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbcnetworkpage',
            name='network_focus_download_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='File (PDF, etc.)'),
        ),
        migrations.AlterField(
            model_name='sbcalliancepage',
            name='alliance_description',
            field=wagtail.fields.RichTextField(default='<p>La alianza entre UNICEF LACRO y la Fundación Universidad del Norte (Uninorte) tiene como propósito fortalecer las capacidades en Cambio Social y de Comportamiento (SBC) en América Latina y el Caribe, a través de la articulación entre academia, sector público y organizaciones sociales.</p><br/><br/><p>Esta colaboración impulsa la creación y consolidación de una Red Académica Regional, orientada a generar conocimiento, formar talento y promover la implementación de estrategias de SBC contextualizadas a las realidades culturales y sociales de la región.</p>'),
        ),
        migrations.AlterField(
            model_name='sbcnetworkpage',
            name='network_description',
            field=wagtail.fields.RichTextField(default='\n            <p>La Red Académica de Intercambio y Aprendizaje sobre Cambio Social y de Comportamiento (SBC) en favor de la infancia en América Latina y el Caribe es una iniciativa impulsada por UNICEF LACRO en alianza con la Universidad del Norte (UNINORTE), orientada a fortalecer la articulación entre la academia, organismos internacionales, gobiernos y sociedad civil para promover transformaciones sociales sostenibles en la región.\n            <br/><br/>\n            La Red surge como resultado de un proceso iniciado en 2023, que ha integrado formación, generación de conocimiento y diálogo regional en torno al enfoque de Cambio Social y de Comportamiento, permitiendo consolidar una base académica y técnica sólida para su desarrollo.\n            <br/><br/>\n            La Red tiene como propósito consolidar una plataforma regional de aprendizaje, investigación e innovación, que contribuya al fortalecimiento de capacidades técnicas, la producción de evidencia y la implementación de estrategias de cambio social y de comportamiento orientadas a mejorar las condiciones de vida de niños, niñas y adolescentes en América Latina y el Caribe.</p>\n        '),
        ),
        migrations.AlterField(
            model_name='sbcnetworkpage',
            name='network_focus_body',
            field=wagtail.fields.RichTextField(default='\n            <p>La Red reúne universidades y actores académicos de América Latina y el Caribe, promoviendo un enfoque:<br/></p>\n            <ul>\n                <li><b>Colaborativo</b>, basado en el diálogo de saberes</li>\n                <li><b>Contextualizado</b>, adaptado a las realidades culturales de la región</li>\n                <li><b>Interdisciplinario</b>, integrando diversas áreas del conocimiento</li>\n                <li><b>Centrado en derechos</b>, con énfasis en la niñez y la equidad</li>\n            </ul>\n            <p><br/>Entre sus áreas prioritarias se encuentran la inmunización, la nutrición, la  educación, la protección contra la violencia, la salud mental, la  inclusión social y la acción climática.</p>\n        '),
        ),
        migrations.AlterField(
            model_name='sbcuniversity',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo'),
        ),
    ]
