# Generated by Django 3.2.25 on 2026-05-06 15:31

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0039_auto_20260506_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbcnetworkpage',
            name='network_team_unicef_list',
            field=wagtail.fields.StreamField([('strategy', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255)), ('subtitle', wagtail.blocks.CharBlock(max_length=255)), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link']))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='sbcnetworkpage',
            name='network_team_unicef_title',
            field=models.CharField(default='Equipo UNICEF', max_length=255),
        ),
        migrations.AddField(
            model_name='sbcnetworkpage',
            name='network_team_uninorte_list',
            field=wagtail.fields.StreamField([('strategy', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255)), ('subtitle', wagtail.blocks.CharBlock(max_length=255)), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link']))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='sbcnetworkpage',
            name='network_team_uninorte_title',
            field=models.CharField(default='Equipo UNICEF', max_length=255),
        ),
    ]
