# Generated by Django 3.2.25 on 2026-05-06 15:32

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0040_auto_20260506_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbcnetworkpage',
            name='network_team_unicef_list',
            field=wagtail.fields.StreamField([('member', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255)), ('subtitle', wagtail.blocks.CharBlock(max_length=255)), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link']))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='sbcnetworkpage',
            name='network_team_uninorte_list',
            field=wagtail.fields.StreamField([('member', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255)), ('subtitle', wagtail.blocks.CharBlock(max_length=255)), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link']))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='sbcnetworkpage',
            name='network_team_uninorte_title',
            field=models.CharField(default='Equipo UNINORTE', max_length=255),
        ),
    ]
