# Generated by Django 3.2.25 on 2026-05-06 15:42

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0042_auto_20260506_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbcnetworkpage',
            name='network_team_unicef_list',
            field=wagtail.fields.StreamField([('member', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255)), ('subtitle', wagtail.blocks.CharBlock(max_length=255, required=False)), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='sbcnetworkpage',
            name='network_team_uninorte_list',
            field=wagtail.fields.StreamField([('member', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255)), ('subtitle', wagtail.blocks.CharBlock(max_length=255, required=False)), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
