# Generated by Django 3.2.25 on 2026-05-11 15:12

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0043_auto_20260506_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbcnetworkpage',
            name='network_universities_list',
            field=wagtail.fields.StreamField([('university', wagtail.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.blocks.URLBlock(require=False))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.DeleteModel(
            name='SBCUniversity',
        ),
    ]
