# Generated by Django 3.2.25 on 2026-05-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0044_auto_20260511_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbcnetworkpage',
            name='network_universities_map',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sbcnetworkpage',
            name='network_universities_title',
            field=models.CharField(default='Universidades Participantes', max_length=255),
        ),
    ]
