# Generated by Django 3.2.25 on 2026-05-11 15:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0045_auto_20260511_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbcnetworkpage',
            name='network_universities_list',
            field=wagtail.fields.StreamField([('university', wagtail.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.blocks.URLBlock(required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
