# Generated by Django 3.2.25 on 2026-05-15 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('sbc', '0046_alter_sbcnetworkpage_network_universities_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbcheader',
            name='unicef_logo',
        ),
        migrations.RemoveField(
            model_name='sbcheader',
            name='university_logo',
        ),
        migrations.AddField(
            model_name='sbcheader',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
