# Generated by Django 3.2.25 on 2026-05-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0047_auto_20260515_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbcresource',
            name='description',
        ),
    ]
