# Generated by Django 3.2.25 on 2026-05-15 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0048_remove_sbcresource_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sbcresource',
            options={'ordering': ['-date'], 'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.AddField(
            model_name='sbcresource',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Published date'),
        ),
    ]
