# Generated by Django 5.2.4 on 2026-06-30 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0049_auto_20260515_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbcfooter',
            name='unicef_link',
            field=models.URLField(blank=True, default='https://unicef.org/', help_text='Link must begin with http:// or https://', null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='sbcfooter',
            name='university_link',
            field=models.URLField(blank=True, default='https://uninorte.edu.co/', help_text='Link must begin with http:// or https://', null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
