# Generated by Django 5.2.4 on 2026-06-30 16:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0050_alter_sbcfooter_unicef_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbcnetworkpage',
            name='network_description',
            field=wagtail.fields.RichTextField(default='\n            <p>La Red Académica de Intercambio y Aprendizaje sobre Cambio Social y de Comportamiento (SBC) en favor de la infancia en América Latina y el Caribe es una iniciativa impulsada por UNICEF LACRO en alianza con la Universidad del Norte (UNINORTE), orientada a fortalecer la articulación entre la academia, organismos internacionales, gobiernos y sociedad civil para promover transformaciones sociales sostenibles en la región.\n            </p>\n            <p>\n            La Red surge como resultado de un proceso iniciado en 2023, que ha integrado formación, generación de conocimiento y diálogo regional en torno al enfoque de Cambio Social y de Comportamiento, permitiendo consolidar una base académica y técnica sólida para su desarrollo.\n            </p>\n            <p>\n            La Red tiene como propósito consolidar una plataforma regional de aprendizaje, investigación e innovación, que contribuya al fortalecimiento de capacidades técnicas, la producción de evidencia y la implementación de estrategias de cambio social y de comportamiento orientadas a mejorar las condiciones de vida de niños, niñas y adolescentes en América Latina y el Caribe.</p>\n        '),
        ),
        migrations.AlterField(
            model_name='sbcnetworkpage',
            name='network_focus_body',
            field=wagtail.fields.RichTextField(default='\n            <p>La Red reúne universidades y actores académicos de América Latina y el Caribe, promoviendo un enfoque:</p>\n            <ul>\n                <li><b>Colaborativo</b>, basado en el diálogo de saberes</li>\n                <li><b>Contextualizado</b>, adaptado a las realidades culturales de la región</li>\n                <li><b>Interdisciplinario</b>, integrando diversas áreas del conocimiento</li>\n                <li><b>Centrado en derechos</b>, con énfasis en la niñez y la equidad</li>\n            </ul>\n            <p>Entre sus áreas prioritarias se encuentran la inmunización, la nutrición, la  educación, la protección contra la violencia, la salud mental, la  inclusión social y la acción climática.</p>\n        '),
        ),
    ]
