# Generated by Django 3.2.19 on 2023-06-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments_xtd', '0008_auto_20200920_2037'),
        ('comments', '0003_commentmoderation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentModeration',
            new_name='CommunityCommentModeration',
        ),
        migrations.AlterModelOptions(
            name='communitycommentmoderation',
            options={'permissions': (('can_community_moderate', 'Can moderate comments on public site'),)},
        ),
    ]
