# Generated by Django 3.2.19 on 2023-05-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments_xtd', '0008_auto_20200920_2037'),
        ('comments', '0004_auto_20230522_1650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentModeration',
            new_name='CommunityCommentModeration',
        ),
        migrations.AlterModelOptions(
            name='communitycommentmoderation',
            options={'permissions': (('can_community_moderate', 'Can moderate comments on PUBLIC SITE'),)},
        ),
    ]
