# Generated by Django 3.2.23 on 2024-02-12 11:22

import cranky_uncle.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('cranky_uncle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrankyUncleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RapidPro',
            fields=[
                ('rapidpro_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('quick_replies', models.JSONField(blank=True, null=True)),
                ('to', models.CharField(max_length=255)),
                ('from_field', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('flow_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrankyUncle',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.StreamField([('cranky_uncle_bot', wagtail.core.blocks.StructBlock([('subject', wagtail.core.blocks.CharBlock()), ('button_text', wagtail.core.blocks.CharBlock()), ('trigger_string', wagtail.core.blocks.CharBlock()), ('cranky_uncle_channel', cranky_uncle.blocks.CrankyUncleChannelChooserBlock())]))], blank=True, null=True)),
                ('lead_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
