# Generated by Django 3.2.23 on 2024-02-13 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cranky_uncle', '0002_crankyuncle_crankyuncleindexpage_rapidpro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crankyuncle',
            options={'verbose_name': 'Cranky', 'verbose_name_plural': 'Cranky Uncle'},
        ),
    ]
