# Generated by Django 3.2.23 on 2024-02-15 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cranky_uncle', '0003_alter_crankyuncle_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crankyuncle',
            name='body',
        ),
        migrations.RemoveField(
            model_name='crankyuncle',
            name='lead_image',
        ),
        migrations.AddField(
            model_name='crankyuncle',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crankyuncle',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cranky_uncle.crankyunclechannel'),
        ),
        migrations.AddField(
            model_name='crankyuncle',
            name='trigger_string',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
