# Generated by Django 3.1.12 on 2021-06-25 13:18

from django.db import migrations
import questionnaires.blocks
import wagtail.core.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyformfield',
            name='skip_logic',
            field=questionnaires.blocks.SkipLogicField([('skip_logic', wagtail.core.blocks.StructBlock([('choice', wagtail.core.blocks.CharBlock(required=False)), ('skip_logic', wagtail.core.blocks.ChoiceBlock(choices=[('next', 'Next default question'), ('end', 'End of survey')])), ('question', wagtail.core.blocks.IntegerBlock(required=False))]))], blank=True, verbose_name='Answer options'),
        ),
    ]
