# Generated by Django 3.1.12 on 2021-06-14 23:40

from django.db import migrations, models
import django.db.models.deletion
import home.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='allow_anonymous_submissions',
            field=models.BooleanField(default=True, help_text='Check this to allow users who are NOT logged in to complete surveys.'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='thank_you_internal_link',
            field=models.ForeignKey(blank=True, help_text='Optional page to which user after questions can go', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questionnaires_poll_related', to='wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True)),
                ('thank_you_text', wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('media', home.blocks.MediaBlock(icon='media')), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True)),
                ('thank_you_link_text', models.CharField(blank=True, default='Check more', help_text='Text to be linked', max_length=40, null=True)),
                ('thank_you_external_link', models.URLField(blank=True, help_text='Optional external link to which user after questions can go e.g., https://www.google.com', null=True)),
                ('allow_anonymous_submissions', models.BooleanField(default=True, help_text='Check this to allow users who are NOT logged in to complete surveys.')),
                ('thank_you_internal_link', models.ForeignKey(blank=True, help_text='Optional page to which user after questions can go', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questionnaires_survey_related', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'survey',
                'verbose_name_plural': 'surveys',
            },
            bases=('wagtailcore.page',),
        ),
    ]
