# Generated by Django 3.1.11 on 2021-07-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'poll', 'verbose_name_plural': 'polls'},
        ),
    ]
