# Generated by Django 3.1.12 on 2021-06-15 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('questionnaires', '0002_auto_20210614_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='allow_multiple_submissions',
            field=models.BooleanField(default=True, help_text='Check this to allow multiple form submissions for users'),
        ),
        migrations.AddField(
            model_name='poll',
            name='start_button_required',
            field=models.BooleanField(default=False, help_text='Check this to demand clicking start before showing questionnaire options'),
        ),
        migrations.AddField(
            model_name='poll',
            name='start_button_text',
            field=models.CharField(default='Start', help_text='Start button text', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='submit_button_text',
            field=models.CharField(default='Submit', help_text='Submit button text', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='allow_multiple_submissions',
            field=models.BooleanField(default=True, help_text='Check this to allow multiple form submissions for users'),
        ),
        migrations.AddField(
            model_name='survey',
            name='start_button_required',
            field=models.BooleanField(default=False, help_text='Check this to demand clicking start before showing questionnaire options'),
        ),
        migrations.AddField(
            model_name='survey',
            name='start_button_text',
            field=models.CharField(default='Start', help_text='Start button text', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='submit_button_text',
            field=models.CharField(default='Submit', help_text='Submit button text', max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.TextField()),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='submit time')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.page')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'form submission',
                'verbose_name_plural': 'form submissions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyFormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.CharField(blank=True, help_text='Default value. Comma separated values supported for checkboxes.', max_length=255, verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='questionnaires.survey')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
