# Generated by Django 3.1.13 on 2021-07-23 09:06

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_auto_20210720_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizformfield',
            name='skip_logic',
            field=wagtail.core.fields.StreamField([('skip_logic', wagtail.core.blocks.StructBlock([('choice', wagtail.core.blocks.CharBlock(required=False)), ('skip_logic', wagtail.core.blocks.ChoiceBlock(choices=[('next', 'Next default question'), ('end', 'End of survey'), ('question', 'Another question')], required=False)), ('question', wagtail.core.blocks.IntegerBlock(required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='surveyformfield',
            name='skip_logic',
            field=wagtail.core.fields.StreamField([('skip_logic', wagtail.core.blocks.StructBlock([('choice', wagtail.core.blocks.CharBlock(required=False)), ('skip_logic', wagtail.core.blocks.ChoiceBlock(choices=[('next', 'Next default question'), ('end', 'End of survey'), ('question', 'Another question')], required=False)), ('question', wagtail.core.blocks.IntegerBlock(required=False))]))], blank=True),
        ),
    ]
