# Generated by Django 3.1.12 on 2021-06-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_quiz_quizformfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='direct_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='direct_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='direct_display',
            field=models.BooleanField(default=False),
        ),
    ]
