# Generated by Django 3.1.13 on 2021-07-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_auto_20210630_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='multi_step',
            field=models.BooleanField(default=False, help_text='Whether to display the survey questions to the user one at a time, instead of all at once.', verbose_name='Multi-step'),
        ),
    ]
