# Generated by Django 3.1.11 on 2021-07-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0006_auto_20210728_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollformfield',
            name='field_type',
            field=models.CharField(choices=[('checkboxes', 'Checkboxes'), ('dropdown', 'Dropdown'), ('radio', 'Radio buttons')], max_length=16, verbose_name='field type'),
        ),
    ]
