# Generated by Django 3.1.13 on 2021-07-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0007_auto_20210728_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizformfield',
            name='correct_answer',
            field=models.CharField(help_text='The correct answer/choice(s). For checkboxes: a comma separated list of choices. For checkbox: Either "on" or "off".', max_length=256, verbose_name='correct_answer'),
        ),
    ]
