# Generated by Django 3.1.13 on 2021-08-02 14:06
from django.core.management import call_command
from django.db import migrations


def _create_index_pages(apps, schema_editor):
    call_command('create_questionnaires_index_pages')


def _delete_index_pages(apps, schema_editor):
    PollIndexPage = apps.get_model('questionnaires.PollIndexPage')
    SurveyIndexPage = apps.get_model('questionnaires.SurveyIndexPage')
    QuizIndexPage = apps.get_model('questionnaires.QuizIndexPage')

    PollIndexPage.objects.all().delete()
    SurveyIndexPage.objects.all().delete()
    QuizIndexPage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0009_pollindexpage_quizindexpage_surveyindexpage'),
    ]

    operations = [
        migrations.RunPython(_create_index_pages, _delete_index_pages)
    ]
