# Generated by Django 3.1.13 on 2021-08-02 14:06
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0009_pollindexpage_quizindexpage_surveyindexpage'),
    ]

    operations = [
    ]
