# Generated by Django 3.1.13 on 2021-08-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0010_auto_20210802_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
