# Generated by Django 3.1.13 on 2021-08-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0011_usersubmission_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollformfield',
            name='choices',
            field=models.TextField(blank=True, help_text='Pipe (|) separated list of choices.', verbose_name='choices'),
        ),
        migrations.AlterField(
            model_name='quizformfield',
            name='correct_answer',
            field=models.TextField(help_text='The correct answer/choice(s). Pipe (|) separated list of choices. For checkbox: Either "true" or "false".', verbose_name='correct_answer'),
        ),
    ]
