# Generated by Django 3.1.13 on 2021-08-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0011_usersubmission_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollformfield',
            name='choices',
            field=models.TextField(blank=True, help_text='Pipe (|) separated list of choices.', verbose_name='choices'),
        ),
        migrations.AlterField(
            model_name='quizformfield',
            name='correct_answer',
            field=models.TextField(help_text='If multiple choices are correct, separate choices with a pipe (|) symbol.', verbose_name='correct_answer'),
        ),
    ]
