# Generated by Django 3.1.13 on 2021-08-27 10:33

from django.db import migrations
import questionnaires.blocks
import wagtail.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0013_auto_20210825_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyformfield',
            name='skip_logic',
            field=questionnaires.blocks.SkipLogicField([('skip_logic', wagtail.blocks.StructBlock([('choice', wagtail.blocks.CharBlock(required=False)), ('skip_logic', wagtail.blocks.ChoiceBlock(choices=[('next', 'Next default question'), ('end', 'End of survey'), ('question', 'Another question')], required=False)), ('question', questionnaires.blocks.QuestionSelectBlock(help_text='Please save the survey as a draft to populate or update the list of questions.', required=False))]))], blank=True, help_text='<strong>Checkbox must include only 2 Answer Options. true and false in that order.</strong>', null=True, verbose_name='Answer options'),
        ),
    ]
