# Generated by Django 3.1.11 on 2021-08-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0014_auto_20210827_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizformfield',
            name='choices',
            field=models.TextField(blank=True, help_text='For checkboxes, dropdown and radio: Pipe (|) separated list of choices.', verbose_name='choices'),
        ),
        migrations.AlterField(
            model_name='quizformfield',
            name='correct_answer',
            field=models.TextField(help_text='The correct answer/choice(s). If multiple choices are correct, separate choices with a pipe (|) symbol. For checkbox: Either "true" or "false".', verbose_name='correct_answer'),
        ),
        migrations.AlterField(
            model_name='quizformfield',
            name='field_type',
            field=models.CharField(choices=[('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('date', 'Date'), ('datetime', 'Date/time'), ('dropdown', 'Drop down'), ('email', 'Email'), ('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('number', 'Number'), ('positivenumber', 'Positive number'), ('radio', 'Radio buttons'), ('url', 'URL')], max_length=16, verbose_name='field type'),
        ),
        migrations.AlterField(
            model_name='surveyformfield',
            name='field_type',
            field=models.CharField(choices=[('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('date', 'Date'), ('datetime', 'Date/time'), ('dropdown', 'Drop down'), ('email', 'Email'), ('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('number', 'Number'), ('positivenumber', 'Positive number'), ('radio', 'Radio buttons'), ('url', 'URL')], max_length=16, verbose_name='field type'),
        ),
    ]
