# Generated by Django 3.1.13 on 2021-08-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0015_auto_20210827_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollformfield',
            name='choices',
            field=models.TextField(blank=True, help_text='Pipe (|) separated list of choices.', null=True, verbose_name='choices'),
        ),
        migrations.AlterField(
            model_name='pollformfield',
            name='field_type',
            field=models.CharField(choices=[('checkboxes', 'Checkboxes'), ('dropdown', 'Dropdown'), ('multiline', 'Multi-line text'), ('radio', 'Radio buttons')], max_length=16, verbose_name='field type'),
        ),
    ]
