# Generated by Django 3.1.13 on 2021-08-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0015_auto_20210827_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollformfield',
            name='default_value',
            field=models.TextField(blank=True, help_text='Default value. Pipe (|) separated values supported for checkboxes.', verbose_name='default value'),
        ),
        migrations.AlterField(
            model_name='quizformfield',
            name='default_value',
            field=models.TextField(blank=True, help_text='Default value. Pipe (|) separated values supported for checkboxes.', verbose_name='default value'),
        ),
        migrations.AlterField(
            model_name='surveyformfield',
            name='default_value',
            field=models.TextField(blank=True, help_text='Default value. Pipe (|) separated values supported for checkboxes.', verbose_name='default value'),
        ),
    ]
