# Generated by Django 3.1.13 on 2021-09-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0017_auto_20210901_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollformfield',
            name='clean_name',
            field=models.TextField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='quizformfield',
            name='clean_name',
            field=models.TextField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='surveyformfield',
            name='clean_name',
            field=models.TextField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', verbose_name='name'),
        ),
    ]
