# Generated by Django 3.1.13 on 2021-09-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0017_auto_20210901_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='randomise_options',
            field=models.BooleanField(default=False, help_text='Randomising the options allows the options to be shown in a different order each time the page is displayed.'),
        ),
        migrations.AddField(
            model_name='pollformfield',
            name='admin_label',
            field=models.CharField(help_text='Column header used during CSV export of poll responses.', max_length=256, null=True, verbose_name='admin_label'),
        ),
    ]
