# Generated by Django 3.1.13 on 2021-09-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0018_auto_20210921_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='index_page_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='index_page_description_line_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='index_page_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='index_page_description_line_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='index_page_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='index_page_description_line_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
