# Generated by Django 3.1.13 on 2021-10-04 11:13

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0018_auto_20210929_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='index_page_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='index_page_description_line_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='randomise_options',
            field=models.BooleanField(default=False, help_text='Randomising the options allows the options to be shown in a different order each time the page is displayed.'),
        ),
        migrations.AddField(
            model_name='poll',
            name='terms_and_conditions',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('page_button', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('text', wagtail.core.blocks.CharBlock(max_length=255, required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pollformfield',
            name='admin_label',
            field=models.CharField(help_text='Column header used during CSV export of poll responses.', max_length=256, null=True, verbose_name='admin_label'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='index_page_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='index_page_description_line_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='terms_and_conditions',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('page_button', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('text', wagtail.core.blocks.CharBlock(max_length=255, required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='index_page_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='index_page_description_line_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='terms_and_conditions',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('page_button', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('text', wagtail.core.blocks.CharBlock(max_length=255, required=False))]))], blank=True, null=True),
        ),
    ]
