# Generated by Django 3.1.13 on 2021-10-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0022_auto_20211026_1023'),
        ('questionnaires', '0022_auto_20211027_0902'),
    ]

    operations = [
    ]
