# Generated by Django 3.1.14 on 2021-12-21 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('questionnaires', '0023_poll_show_results_with_no_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='image_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='image_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='survey',
            name='image_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
    ]
