# Generated by Django 3.1.14 on 2022-01-25 11:49

import re

from django.db import migrations


def _fix_poll_paragraph_image_format(apps, schema_editor):
    Poll = apps.get_model('questionnaires', 'Poll')
    format_regex = re.compile('format=["|\'][\w|-]+["|\']')
    polls = Poll.objects.all()
    for poll in polls:
        for block in poll.description.stream_data:
            if block.get('type') in 'paragraph':
                block['value'] = format_regex.sub('format="full-width"', block.get('value'))

        for block in poll.thank_you_text.stream_data:
            if block.get('type') in 'paragraph':
                block['value'] = format_regex.sub('format="full-width"', block.get('value'))

        for block in poll.terms_and_conditions.stream_data:
            if block.get('type') in 'paragraph':
                block['value'] = format_regex.sub('format="full-width"', block.get('value'))

    Poll.objects.bulk_update(polls, fields=['description', 'thank_you_text', 'terms_and_conditions'], batch_size=100)


def _fix_survey_paragraph_image_format(apps, schema_editor):
    Survey = apps.get_model('questionnaires', 'Survey')
    format_regex = re.compile('format=["|\'][\w|-]+["|\']')
    surveys = Survey.objects.all()
    for survey in surveys:
        for block in survey.description.stream_data:
            if block.get('type') in 'paragraph':
                block['value'] = format_regex.sub('format="full-width"', block.get('value'))

        for block in survey.thank_you_text.stream_data:
            if block.get('type') in 'paragraph':
                block['value'] = format_regex.sub('format="full-width"', block.get('value'))

        for block in survey.terms_and_conditions.stream_data:
            if block.get('type') in 'paragraph':
                block['value'] = format_regex.sub('format="full-width"', block.get('value'))

    Survey.objects.bulk_update(surveys, fields=['description', 'thank_you_text', 'terms_and_conditions'], batch_size=100)


def _fix_quiz_paragraph_image_format(apps, schema_editor):
    Quiz = apps.get_model('questionnaires', 'Quiz')
    format_regex = re.compile('format=["|\'][\w|-]+["|\']')
    quizzes = Quiz.objects.all()
    for quiz in quizzes:
        for block in quiz.description.stream_data:
            if block.get('type') in 'paragraph':
                block['value'] = format_regex.sub('format="full-width"', block.get('value'))

        for block in quiz.thank_you_text.stream_data:
            if block.get('type') in 'paragraph':
                block['value'] = format_regex.sub('format="full-width"', block.get('value'))

        for block in quiz.terms_and_conditions.stream_data:
            if block.get('type') in 'paragraph':
                block['value'] = format_regex.sub('format="full-width"', block.get('value'))

    Quiz.objects.bulk_update(quizzes, fields=['description', 'thank_you_text', 'terms_and_conditions'], batch_size=100)


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0026_auto_20220125_1149'),
    ]

    operations = [
        migrations.RunPython(_fix_poll_paragraph_image_format, migrations.RunPython.noop),
        migrations.RunPython(_fix_survey_paragraph_image_format, migrations.RunPython.noop),
        migrations.RunPython(_fix_quiz_paragraph_image_format, migrations.RunPython.noop),
    ]
