# Generated by Django 3.1.14 on 2022-01-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0026_auto_20220125_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollformfield',
            name='label',
            field=models.TextField(help_text='The label of the form field', verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='quizformfield',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedback message for user answer.', null=True, verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='quizformfield',
            name='label',
            field=models.TextField(help_text='The label of the form field', verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='surveyformfield',
            name='label',
            field=models.TextField(help_text='The label of the form field', verbose_name='label'),
        ),
    ]
