# Generated by Django 3.1.14 on 2022-04-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0027_auto_20220128_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyformfield',
            name='required',
            field=models.BooleanField(default=True, verbose_name='required'),
        ),
    ]
