# Generated by Django 3.1.14 on 2022-02-03 12:22

from django.db import migrations


def _fix_skip_logic(apps, schema_editor):
    SurveyFormField = apps.get_model('questionnaires.SurveyFormField')
    survey_form_fields = SurveyFormField.objects.all()
    for survey_form_field in survey_form_fields:
        if survey_form_field.skip_logic:
            skip_logics = survey_form_field.skip_logic.stream_data
            for skip_logic in skip_logics:
                skip_logic.get('value', {}).pop('survey')

    SurveyFormField.objects.bulk_update(survey_form_fields, fields=['skip_logic'], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0027_auto_20220128_1047'),
    ]

    operations = [
        migrations.RunPython(_fix_skip_logic, migrations.RunPython.noop)
    ]
