# Generated by Django 3.1.14 on 2022-05-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0028_auto_20220405_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollformfield',
            name='clean_name',
            field=models.TextField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case. This will appear in the HTML but will not be visible to the user', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='quizformfield',
            name='clean_name',
            field=models.TextField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case. This will appear in the HTML but will not be visible to the user', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='surveyformfield',
            name='clean_name',
            field=models.TextField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case. This will appear in the HTML but will not be visible to the user', verbose_name='name'),
        ),
    ]
