# Generated by Django 3.1.14 on 2023-02-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0029_auto_20220512_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizformfield',
            name='survey_question',
            field=models.BooleanField(default=False, help_text='Do not show this question on the results page, or include in quiz scoring.', verbose_name='Survey Question'),
        ),
    ]
