# Generated by Django 3.1.14 on 2022-10-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0029_auto_20220512_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='display_feedback',
            field=models.BooleanField(default=True),
        ),
    ]
