# Generated by Django 3.2.25 on 2025-02-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0030_enable_use_json_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_category', models.CharField(choices=[('Child', 'Child'), ('Youth', 'Youth'), ('Adult', 'Adult'), ('Senior', 'Senior')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'registration_survey',
            },
        ),
    ]
