# Generated by Django 3.2.25 on 2024-06-03 10:05

from django.db import migrations
import home.blocks
import questionnaires.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaires", "0030_enable_use_json_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="description",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(
                            form_classname="full title",
                            icon="h1",
                            template="blocks/heading.html",
                        ),
                    ),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("paragraph_v1_legacy", home.blocks.RawHTMLBlock(icon="code")),
                    (
                        "image",
                        wagtail.images.blocks.ImageChooserBlock(
                            template="blocks/image.html"
                        ),
                    ),
                    ("list", wagtailmarkdown.blocks.MarkdownBlock()),
                    (
                        "numbered_list",
                        home.blocks.NumberedListBlock(
                            wagtailmarkdown.blocks.MarkdownBlock()
                        ),
                    ),
                    (
                        "page_button",
                        wagtail.blocks.StructBlock(
                            [
                                ("page", wagtail.blocks.PageChooserBlock()),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        max_length=255, required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="terms_and_conditions",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "page_button",
                        wagtail.blocks.StructBlock(
                            [
                                ("page", wagtail.blocks.PageChooserBlock()),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        max_length=255, required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="thank_you_text",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("media", home.blocks.MediaBlock()),
                    (
                        "image",
                        wagtail.images.blocks.ImageChooserBlock(
                            template="blocks/image.html"
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="description",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(
                            form_classname="full title",
                            icon="h1",
                            template="blocks/heading.html",
                        ),
                    ),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("paragraph_v1_legacy", home.blocks.RawHTMLBlock(icon="code")),
                    (
                        "image",
                        wagtail.images.blocks.ImageChooserBlock(
                            template="blocks/image.html"
                        ),
                    ),
                    ("list", wagtailmarkdown.blocks.MarkdownBlock()),
                    (
                        "numbered_list",
                        home.blocks.NumberedListBlock(
                            wagtailmarkdown.blocks.MarkdownBlock()
                        ),
                    ),
                    (
                        "page_button",
                        wagtail.blocks.StructBlock(
                            [
                                ("page", wagtail.blocks.PageChooserBlock()),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        max_length=255, required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="terms_and_conditions",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "page_button",
                        wagtail.blocks.StructBlock(
                            [
                                ("page", wagtail.blocks.PageChooserBlock()),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        max_length=255, required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="thank_you_text",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("media", home.blocks.MediaBlock()),
                    (
                        "image",
                        wagtail.images.blocks.ImageChooserBlock(
                            template="blocks/image.html"
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="description",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(
                            form_classname="full title",
                            icon="h1",
                            template="blocks/heading.html",
                        ),
                    ),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("paragraph_v1_legacy", home.blocks.RawHTMLBlock(icon="code")),
                    (
                        "image",
                        wagtail.images.blocks.ImageChooserBlock(
                            template="blocks/image.html"
                        ),
                    ),
                    ("list", wagtailmarkdown.blocks.MarkdownBlock()),
                    (
                        "numbered_list",
                        home.blocks.NumberedListBlock(
                            wagtailmarkdown.blocks.MarkdownBlock()
                        ),
                    ),
                    (
                        "page_button",
                        wagtail.blocks.StructBlock(
                            [
                                ("page", wagtail.blocks.PageChooserBlock()),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        max_length=255, required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="terms_and_conditions",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "page_button",
                        wagtail.blocks.StructBlock(
                            [
                                ("page", wagtail.blocks.PageChooserBlock()),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        max_length=255, required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="thank_you_text",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("media", home.blocks.MediaBlock()),
                    (
                        "image",
                        wagtail.images.blocks.ImageChooserBlock(
                            template="blocks/image.html"
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="surveyformfield",
            name="skip_logic",
            field=questionnaires.blocks.SkipLogicField(
                [
                    (
                        "skip_logic",
                        wagtail.blocks.StructBlock(
                            [
                                ("choice", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "skip_logic",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("next", "Next default question"),
                                            ("end", "End of survey"),
                                            ("question", "Another question"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "question",
                                    questionnaires.blocks.QuestionSelectBlock(
                                        help_text="Please save the survey as a draft to populate or update the list of questions.",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="<strong>Checkbox must include exactly 2 Skip Logic Options: true and false, in that order.</strong>",
                null=True,
                use_json_field=True,
                verbose_name="Answer options",
            ),
        ),
    ]
