# Generated by Django 5.2.4 on 2025-10-22 08:11

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0033_survey_notification_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('choice_text', models.CharField(help_text='The option text that users will see', max_length=255, verbose_name='Choice Text')),
                ('is_correct', models.BooleanField(default=False, help_text='Mark this choice as the correct answer.', verbose_name='Correct Answer')),
                ('feedback', models.TextField(blank=True, help_text='Feedback specific to this choice (optional).', null=True, verbose_name='Feedback')),
                ('question', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_choices', to='questionnaires.quizformfield')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
