# Generated by Django 5.2.4 on 2025-10-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0034_quizchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizchoice',
            name='is_correct',
        ),
    ]
