# Generated by Django 3.1.11 on 2021-05-31 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0022_uploadedimage"),
        ("wagtailcore", "0059_apply_collection_ordering"),
        ("home", "0004_auto_20210409_1243"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "show_results",
                    models.BooleanField(
                        default=True,
                        help_text="This option allows the users to see the results.",
                    ),
                ),
                (
                    "randomise_options",
                    models.BooleanField(
                        default=False,
                        help_text="Randomising the options allows the options to be shown in a different order each time the page is displayed.",
                    ),
                ),
                (
                    "result_as_percentage",
                    models.BooleanField(
                        default=True,
                        help_text="If not checked, the results will be shown as a total instead of a percentage.",
                    ),
                ),
                (
                    "allow_multiple_choice",
                    models.BooleanField(
                        default=False,
                        help_text="Allows the user to choose more than one option.",
                    ),
                ),
                (
                    "is_login_required",
                    models.BooleanField(
                        default=False, help_text="Allows not logged in to vote?"
                    ),
                ),
                (
                    "confirmation_text",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="If added, this url will be used secondarily",
                        null=True,
                    ),
                ),
                (
                    "confirmation_link_text",
                    models.CharField(
                        blank=True,
                        default="Check more",
                        help_text="Text to be linked",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "confirmation_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Add image to result page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "internal_link",
                    models.ForeignKey(
                        blank=True,
                        help_text="If selected, this url will be used first",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
            bases=("wagtailcore.page",),
        ),
    ]
