# Generated by Django 3.1.11 on 2021-05-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormPage',
            new_name='PollPage',
        ),
    ]
