# Generated by Django 3.1.13 on 2021-07-07 07:02

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailsvg', '0002_svg_edit_code'),
        ('home', '0002_auto_20210707_0742'),
        ('wagtailimages', '0022_uploadedimage'),
        ('questionnaires', '0001_initial'),
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='registration_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaires.survey'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site'),
        ),
        migrations.AddField(
            model_name='sectiontaggeditem',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='home.section'),
        ),
        migrations.AddField(
            model_name='sectiontaggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_sectiontaggeditem_items', to='taggit.tag'),
        ),
        migrations.AddField(
            model_name='section',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailsvg.svg'),
        ),
        migrations.AddField(
            model_name='section',
            name='lead_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='section',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.SectionTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='iogtflatmenuitem',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailsvg.svg'),
        ),
        migrations.AddField(
            model_name='iogtflatmenuitem',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.page', verbose_name='link to an internal page'),
        ),
        migrations.AddField(
            model_name='iogtflatmenuitem',
            name='menu',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='iogt_flat_menu_items', to='wagtailmenus.flatmenu'),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='banner_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bannerpage'),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='source',
            field=modelcluster.fields.ParentalKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_banners', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='featuredcontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='featuredcontent',
            name='source',
            field=modelcluster.fields.ParentalKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_content', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='cachesettings',
            name='site',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site'),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='banner_background_image',
            field=models.ForeignKey(blank=True, help_text='Background image', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='banner_icon_button',
            field=models.ForeignKey(blank=True, help_text='Icon Button', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='Image to display as the banner', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='banner_link_page',
            field=models.ForeignKey(blank=True, help_text='Optional page to which the banner will link to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='banners', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='articletaggeditem',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='home.article'),
        ),
        migrations.AddField(
            model_name='articletaggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_articletaggeditem_items', to='taggit.tag'),
        ),
        migrations.AddField(
            model_name='articlerecommendation',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.article'),
        ),
        migrations.AddField(
            model_name='articlerecommendation',
            name='source',
            field=modelcluster.fields.ParentalKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_articles', to='home.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailsvg.svg'),
        ),
        migrations.AddField(
            model_name='article',
            name='lead_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.ArticleTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
