# Generated by Django 3.1.13 on 2021-07-07 10:05
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210707_0702'),
        ('wagtail_localize', '0012_localesynchronization'),
    ]

    operations = [
    ]
