# Generated by Django 3.1.11 on 2021-06-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210409_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
