# Generated by Django 3.1.11 on 2021-07-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_manifestsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
    ]
