# Generated by Django 3.1.12 on 2021-06-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_article_allow_comments'),
        ('home', '0005_auto_20210527_0541'),
    ]

    operations = [
    ]
