# Generated by Django 3.1.11 on 2021-06-02 15:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0005_delete_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('logos', wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock(required=False))], blank=True)),
                ('navigation', wagtail.core.fields.StreamField([('link_group', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('links', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.PageChooserBlock())]))], required=False))], blank=True)),
                ('essential', wagtail.core.fields.StreamField([('page', wagtail.core.blocks.PageChooserBlock())])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FeaturedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.page')),
                ('source', modelcluster.fields.ParentalKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_content', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('external_link', models.URLField(blank=True, help_text='Optional external link which a banner will link to e.g., https://www.google.com', null=True)),
                ('banner_image', models.ForeignKey(help_text='Image to display as the banner', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('banner_link_page', models.ForeignKey(blank=True, help_text='Optional page to which the banner will link to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='banners', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
