# Generated by Django 3.1.9 on 2021-05-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_commentable',
            field=models.BooleanField(default=True),
        ),
    ]
