# Generated by Django 3.1.12 on 2021-06-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210608_1116'),
        ('home', '0006_auto_20210607_1533'),
    ]

    operations = [
    ]
