# Generated by Django 3.1.12 on 2021-06-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_bannerindexpage_bannerpage_featuredcontent_homepagebanner'),
        ('home', '0008_merge_20210608_1407'),
    ]

    operations = [
    ]
