# Generated by Django 3.1.13 on 2021-08-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0008_auto_20210810_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_background_color', models.CharField(blank=True, default='#FFFFFF', help_text='The background color of the website', max_length=8, null=True)),
                ('header_background_color', models.CharField(blank=True, default='#FFFFFF', help_text='The background color of the header background as a HEX code', max_length=8, null=True)),
                ('language_picker_background_color', models.CharField(blank=True, default='#FDD256', help_text='The background color of the language picker button as a HEX code', max_length=8, null=True)),
                ('language_picker_font_color', models.CharField(blank=True, default='#303030', help_text='The font color of the language picker button as a HEX code', max_length=8, null=True)),
                ('section_listing_questionnaire_background_color', models.CharField(blank=True, default='#f0f0f0', help_text='The background color of the Questionnaire in section listing as a HEX code', max_length=8, null=True)),
                ('section_listing_questionnaire_font_color', models.CharField(blank=True, default='#444', help_text='The font color of the Questionnaire in section listing as a HEX code', max_length=8, null=True)),
                ('article_card_font_color', models.CharField(blank=True, default='#444', help_text='The background color of the Quiz in section listing as a HEX code', max_length=8, null=True)),
                ('article_card_background_color', models.CharField(blank=True, default='#ffffff', help_text='The background color of the Quiz in section listing as a HEX code', max_length=8, null=True)),
                ('primary_button_font_color', models.CharField(blank=True, default='#444', help_text='The font/icon color of the primary button as a HEX code', max_length=8, null=True)),
                ('primary_button_background_color', models.CharField(blank=True, default='#f0f0f0', help_text='The background color of the primary button as a HEX code', max_length=8, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
