# Generated by Django 3.1.12 on 2021-06-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_merge_20210609_0608'),
        ('home', '0008_auto_20210609_0530'),
    ]

    operations = [
    ]
