# Generated by Django 3.1.12 on 2021-06-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_merge_20210609_0608'),
        ('home', '0005_auto_20210526_1114'),
    ]

    operations = [
    ]
