# Generated by Django 3.1.13 on 2021-09-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_v1tov2objectmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='v1tov2objectmap',
            name='extra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
