# Generated by Django 3.1.12 on 2021-06-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_cachesettings'),
        ('home', '0008_auto_20210609_0530'),
    ]

    operations = [
    ]
