# Generated by Django 3.1.13 on 2021-09-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_v1tov2objectmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='opt_in_to_google_web_light',
            field=models.BooleanField(default=False),
        ),
    ]
