# Generated by Django 3.1.12 on 2021-06-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_merge_20210616_1048'),
        ('home', '0010_merge_20210617_1019'),
    ]

    operations = [
    ]
