# Generated by Django 3.1.12 on 2021-06-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_manifestsettings'),
        ('home', '0011_merge_20210622_1115'),
    ]

    operations = [
    ]
