# Generated by Django 3.1.12 on 2021-06-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_merge_20210616_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachesettings',
            name='cache',
            field=models.BooleanField(default=True, help_text='provide users with the ability to cache the website content', verbose_name='Enable caching?'),
        ),
    ]
