# Generated by Django 3.1.12 on 2021-06-23 05:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0011_merge_20210622_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_only_translated_pages', models.BooleanField(default=False, help_text='When selecting this option, untranslated pages will not be visible to the front end user when viewing a child language of the site')),
                ('fb_analytics_app_id', models.CharField(blank=True, help_text='The tracking ID to be used to view Facebook Analytics', max_length=25, null=True, verbose_name='Facebook Analytics App ID')),
                ('local_ga_tag_manager', models.CharField(blank=True, help_text='Local GA Tag Manager tracking code (e.g GTM-XXX) to be used to view analytics on this site only', max_length=255, null=True, verbose_name='Local GA Tag Manager')),
                ('global_ga_tag_manager', models.CharField(blank=True, help_text='Global GA Tag Manager tracking code (e.g GTM-XXX) to be used to view analytics on more than one site globally', max_length=255, null=True, verbose_name='Global GA Tag Manager')),
                ('local_ga_tracking_code', models.CharField(blank=True, help_text='Local GA tracking code to be used to view analytics on this site only', max_length=255, null=True, verbose_name='Local GA Tracking Code')),
                ('global_ga_tracking_code', models.CharField(blank=True, help_text='Global GA tracking code to be used to view analytics on more than one site globally', max_length=255, null=True, verbose_name='Global GA Tracking Code')),
                ('social_media_link', wagtail.core.fields.StreamField([('social_media_link', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255)), ('link', wagtail.core.blocks.URLBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True)),
                ('social_media_content_sharing_button', wagtail.core.fields.StreamField([('social_media_content_sharing_button', wagtail.core.blocks.StructBlock([('platform', wagtail.core.blocks.CharBlock(max_length=255)), ('is_active', wagtail.core.blocks.BooleanBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True)),
                ('media_file_size_threshold', models.IntegerField(default=9437184, help_text='Show warning if uploaded media file size is greater than this in bytes. Default is 9 MB')),
                ('allow_anonymous_comment', models.BooleanField(default=False)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
