# Generated by Django 3.1.11 on 2021-09-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_sitesettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='opt_in_to_google_web_light',
            field=models.BooleanField(default=False),
        ),
    ]
