# Generated by Django 3.1.8 on 2021-06-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_merge_20210622_1115'),
        ('home', '0011_merge_20210622_0812'),
    ]

    operations = [
    ]
