# Generated by Django 3.1.12 on 2021-06-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_merge_20210623_1221'),
        ('home', '0012_sitesettings'),
    ]

    operations = [
    ]
