# Generated by Django 3.1.12 on 2021-06-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210616_1542'),
        ('home', '0010_merge_20210617_1019'),
    ]

    operations = [
    ]
