# Generated by Django 3.1.13 on 2021-09-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_sitesettings_opt_in_to_google_web_light'),
        ('home', '0011_v1tov2objectmap_extra'),
    ]

    operations = [
    ]
