# Generated by Django 3.1.13 on 2021-09-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_sitesettings_opt_in_to_google_web_light'),
    ]

    operations = [
        migrations.CreateModel(
            name='SVGToPNGMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_path', models.TextField()),
                ('color', models.TextField()),
                ('png_image_file', models.ImageField(upload_to='svg-to-png-maps/')),
            ],
            options={
                'unique_together': {('svg_path', 'color')},
            },
        ),
    ]
