# Generated by Django 3.1.8 on 2021-09-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_themesettings'),
        ('home', '0012_sitesettings_opt_in_to_google_web_light'),
    ]

    operations = [
    ]
