# Generated by Django 3.1.13 on 2021-09-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_merge_20210920_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='index_page_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
