# Generated by Django 3.1.13 on 2021-10-01 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_merge_20210920_1202'),
        ('home', '0013_svgtopngmap'),
    ]

    operations = [
    ]
