# Generated by Django 3.1.13 on 2021-09-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_merge_20210928_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='mobile_navbar_background_color',
            field=models.CharField(blank=True, default='#0094F4', help_text='The background color of the mobile-only navbar as a HEX code', max_length=8, null=True),
        ),
    ]
