# Generated by Django 3.1.12 on 2021-06-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_merge_20210624_1018'),
        ('home', '0013_merge_20210624_0727'),
    ]

    operations = [
    ]
