# Generated by Django 3.1.12 on 2021-06-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
        ('home', '0014_merge_20210624_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='registration_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaires.survey'),
        ),
    ]
