# Generated by Django 3.1.11 on 2021-10-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_merge_20210920_1202'),
        ('home', '0015_auto_20210930_1308'),
    ]

    operations = [
    ]
