# Generated by Django 3.1.11 on 2021-10-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_merge_20211003_0815'),
        ('home', '0014_article_index_page_description'),
    ]

    operations = [
    ]
