# Generated by Django 3.1.8 on 2021-06-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210624_1618'),
        ('home', '0015_sitesettings_registration_survey'),
    ]

    operations = [
    ]
