# Generated by Django 3.1.13 on 2021-10-13 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0017_merge_20211004_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpage',
            name='banner_link_page',
            field=models.ForeignKey(blank=True, help_text='Optional page to which the banner will link to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='wagtailcore.page'),
        ),
    ]
