# Generated by Django 3.1.12 on 2021-06-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_merge_20210624_1913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectionRecommendation',
        ),
    ]
