# Generated by Django 3.1.8 on 2021-06-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0017_merge_20210624_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache', models.BooleanField(default=True, help_text='check to prompt first time users to download the website as an app', verbose_name='Prompt users to download?')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Cache settings',
            },
        ),
    ]
