# Generated by Django 3.1.11 on 2021-10-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20211007_1256'),
        ('home', '0018_auto_20211013_1158'),
    ]

    operations = [
    ]
