# Generated by Django 3.1.12 on 2021-06-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_cachesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='show_progress_bar',
            field=models.BooleanField(default=False),
        ),
    ]
