# Generated by Django 3.1.13 on 2021-10-18 13:27

from django.db import migrations, models
import django.db.models.deletion
import home.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailsvg', '0002_svg_edit_code'),
        ('home', '0019_merge_20211014_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLinkPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailsvg.svg')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page_link_pages', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', home.mixins.TitleIconMixin),
        ),
    ]
