# Generated by Django 3.1.12 on 2021-06-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_sectionindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='section',
            name='tags',
        ),
        migrations.DeleteModel(
            name='TaggedItem',
        ),
    ]
