# Generated by Django 3.1.11 on 2021-10-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_pagelinkpage'),
        ('home', '0018_svgtopngmap'),
    ]

    operations = [
    ]
