# Generated by Django 3.1.12 on 2021-06-29 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_section_show_progress_bar'),
        ('home', '0021_auto_20210628_1107'),
    ]

    operations = [
    ]
