# Generated by Django 3.2.8 on 2021-11-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20211015_1356'),
        ('home', '0021_merge_20211019_0747'),
    ]

    operations = [
    ]
