# Generated by Django 3.1.13 on 2021-10-20 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0021_merge_20211019_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelinkpage',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_link_pages', to='wagtailcore.page'),
        ),
    ]
