# Generated by Django 3.1.13 on 2021-11-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_merge_20211019_0747'),
        ('home', '0019_auto_20211015_1356'),
    ]

    operations = [
    ]
