# Generated by Django 3.1.11 on 2021-10-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20211015_1356'),
        ('home', '0021_merge_20211019_0747'),
    ]

    operations = [
    ]
