# Generated by Django 3.1.12 on 2021-06-29 09:54

from django.db import migrations, models
import wagtail.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210628_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpage',
            name='banner_desription',
            field=models.TextField(blank=True, help_text='Optional a description for it block', null=True, verbose_name=wagtail.core.models.Page),
        ),
    ]
