# Generated by Django 3.1.12 on 2021-06-29 10:00

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_bannerpage_banner_desription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerpage',
            name='banner_desription',
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='banner_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
