# Generated by Django 3.1.13 on 2021-10-26 07:53

from django.db import migrations, models
import home.blocks
import messaging.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_merge_20211020_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='larger_image_for_top_page_in_list_as_in_v1',
            field=models.BooleanField(default=False),
        ),
    ]
