# Generated by Django 3.1.13 on 2021-10-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20211026_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iogtflatmenuitem',
            old_name='color',
            new_name='background_color',
        ),
        migrations.RenameField(
            model_name='iogtflatmenuitem',
            old_name='color_text',
            new_name='font_color',
        ),
        migrations.RenameField(
            model_name='themesettings',
            old_name='mobile_navbar_background_color',
            new_name='navbar_background_color',
        ),
        migrations.AddField(
            model_name='themesettings',
            name='navbar_font_color',
            field=models.CharField(blank=True, default='#FFFFFF', help_text='The font color of the navbar as a HEX code', max_length=8, null=True),
        ),
    ]
