# Generated by Django 3.1.11 on 2021-10-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20211026_0753'),
        ('home', '0023_auto_20211026_1023'),
    ]

    operations = [
    ]
