# Generated by Django 3.1.12 on 2021-06-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210629_1359'),
        ('home', '0022_merge_20210629_0821'),
    ]

    operations = [
    ]
