# Generated by Django 3.1.13 on 2021-10-25 11:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtailmenus.models.menus
import wagtailmenus.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0023_auto_20211022_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iogtflatmenuitem',
            name='handle',
            field=models.CharField(blank=True, help_text='The handle must be written in this format "[language]_[menu name of your choice]". For example, "en_menu1". If you would  like the menu to be visible on the website you must add "_live" to the end, eg "en_menu1_live". Only one menu per language can be visible at one time.', max_length=100, verbose_name='handle'),
        ),
        migrations.AlterField(
            model_name='iogtflatmenuitem',
            name='link_url',
            field=models.CharField(blank=True, help_text="If you are linking back to a URL on your own IoGT site, be sure to remove the domain and everything before it. For example 'http://sd.goodinternet.org/url/' should instead be '/url/'.", max_length=255, null=True, verbose_name='link to a custom URL'),
        ),
        migrations.CreateModel(
            name='TranslatedFlatMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='For internal reference only.', max_length=255, verbose_name='title')),
                ('heading', models.CharField(blank=True, help_text='If supplied, appears above the menu when rendered.', max_length=255, verbose_name='heading')),
                ('max_levels', models.PositiveSmallIntegerField(choices=[(1, '1: No sub-navigation (flat)'), (2, '2: Allow 1 level of sub-navigation'), (3, '3: Allow 2 levels of sub-navigation'), (4, '4: Allow 3 levels of sub-navigation')], default=1, help_text='The maximum number of levels to display when rendering this menu. The value can be overidden by supplying a different <code>max_levels</code> value to the <code>{% flat_menu %}</code> tag in your templates.', verbose_name='maximum levels')),
                ('handle', models.SlugField(help_text='Used to reference this menu in templates etc. Must be unique for the selected site.', max_length=100, verbose_name='handle')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'flat menu',
                'verbose_name_plural': 'flat menus',
                'abstract': False,
                'unique_together': {('site', 'handle')},
            },
            bases=(wagtailmenus.models.mixins.DefinesSubMenuTemplatesMixin, models.Model, wagtailmenus.models.menus.Menu),
        ),
        migrations.AlterField(
            model_name='iogtflatmenuitem',
            name='menu',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='iogt_flat_menu_items', to='home.translatedflatmenu'),
        ),
    ]
