# Generated by Django 3.1.12 on 2021-06-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210629_1000'),
        ('home', '0022_iogtflatmenuitem'),
    ]

    operations = [
    ]
