# Generated by Django 3.1.13 on 2021-10-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20211029_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iogtflatmenuitem',
            name='handle',
            field=models.CharField(blank=True, help_text='Use this field to optionally specify an additional value for each menu item, which you can then reference in custom menu templates.', max_length=100, verbose_name='handle'),
        ),
    ]
