# Generated by Django 3.1.12 on 2021-06-29 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_merge_20210629_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerpage',
            name='external_link',
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='banner_background_image',
            field=models.ForeignKey(blank=True, help_text='Background image', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='banner_button_text',
            field=models.CharField(blank=True, help_text='The title for a button', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='banner_icon_button',
            field=models.ForeignKey(blank=True, help_text='Icon Button', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='bannerpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='Image to display as the banner', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
    ]
