# Generated by Django 3.1.12 on 2021-06-29 11:15

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_bannerpage_banner_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpage',
            name='banner_background_color',
            field=wagtail_color_panel.fields.ColorField(default='#acc9fa', max_length=7),
        ),
    ]
