# Generated by Django 3.1.13 on 2021-10-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20211027_0902'),
        ('home', '0024_merge_20211027_0807'),
    ]

    operations = [
    ]
