# Generated by Django 3.1.12 on 2021-06-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_delete_sectionrecommendation'),
        ('home', '0024_merge_20210630_0845'),
    ]

    operations = [
    ]
