# Generated by Django 3.1.13 on 2021-10-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20211029_1634'),
    ]

    operations = [
    ]
