# Generated by Django 3.1.12 on 2021-06-29 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0025_bannerpage_banner_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='Image to display as the banner', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
    ]
