# Generated by Django 3.1.12 on 2021-06-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210629_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_polls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_questionnaire',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_survey',
            field=models.BooleanField(default=True),
        ),
    ]
