# Generated by Django 3.1.11 on 2021-10-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20211028_1023'),
        ('home', '0024_auto_20211029_1034'),
    ]

    operations = [
    ]
