# Generated by Django 3.1.11 on 2021-11-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20211110_0848'),
        ('home', '0028_auto_20211110_0645'),
    ]

    operations = [
    ]
