# Generated by Django 3.1.12 on 2021-06-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20210629_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='iogtflatmenuitem',
            name='color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
