# Generated by Django 3.1.13 on 2021-11-09 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0028_sitesettings_apple_touch_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='apple_touch_icon',
            field=models.ForeignKey(blank=True, help_text='Upload an image file (.jpg, .png) to be used as apple touch icon. The ideal size is 120px x 120px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Upload an image file (.jpg, .png). The ideal size is 40px x 40px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Upload an image file (.jpg, .png). The ideal size is 100px x 40px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
