# Generated by Django 3.1.12 on 2021-06-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_iogtflatmenuitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='iogtflatmenuitem',
            name='color_text',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
