# Generated by Django 3.1.13 on 2021-11-16 07:44

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0029_merge_20211111_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestsettings',
            name='icon_196_196',
        ),
        migrations.AddField(
            model_name='manifestsettings',
            name='icon_192_192',
            field=models.ForeignKey(help_text='Add PNG icon 192x192 px (maskable image can be created using https://maskable.app/)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', validators=[home.models.ImageValidator(height=192, width=192)], verbose_name='Icon 192x192 (maskable)'),
        ),
    ]
