# Generated by Django 3.1.11 on 2021-11-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20211123_0720'),
        ('home', '0030_auto_20211116_0744'),
    ]

    operations = [
    ]
