# Generated by Django 3.1.12 on 2021-06-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_iogtflatmenuitem_color_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='show_polls',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='show_questionnaire',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='show_survey',
        ),
    ]
