# Generated by Django 3.1.13 on 2021-11-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_merge_20211123_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='commenting_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='commenting_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='commenting_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('disabled', 'Disabled'), ('timestamped', 'Timestamped'), ('inherited', 'Inherited')], default='inherited', max_length=15),
        ),
        migrations.AlterField(
            model_name='article',
            name='commenting_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('disabled', 'Disabled'), ('timestamped', 'Timestamped'), ('inherited', 'Inherited')], default='inherited', max_length=15),
        ),
        migrations.AlterField(
            model_name='offlineapppage',
            name='commenting_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('disabled', 'Disabled'), ('timestamped', 'Timestamped'), ('inherited', 'Inherited')], default='inherited', max_length=15),
        ),
    ]
