# Generated by Django 3.1.12 on 2021-06-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20210630_0901'),
        ('home', '0026_auto_20210630_0918'),
    ]

    operations = [
    ]
