# Generated by Django 3.1.12 on 2021-06-30 16:51

from django.db import migrations
import home.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_merge_20210630_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='new_featured_content',
            field=wagtail.core.fields.StreamField([('page_button', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('text', wagtail.core.blocks.CharBlock(max_length=255, required=False))])), ('embedded_poll', home.blocks.EmbeddedQuestionnaireChooserBlock(page_type=['questionnaires.Poll'])), ('embedded_survey', home.blocks.EmbeddedQuestionnaireChooserBlock(page_type=['questionnaires.Survey'])), ('article', wagtail.core.blocks.PageChooserBlock(page_type=['home.Article']))], null=True),
        ),
    ]
