# Generated by Django 3.1.12 on 2021-06-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_merge_20210630_0953'),
        ('home', '0027_merge_20210630_1206'),
    ]

    operations = [
    ]
