# Generated by Django 3.1.11 on 2021-12-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20211124_0858'),
        ('home', '0032_auto_20211130_0936'),
    ]

    operations = [
    ]
