# Generated by Django 3.1.12 on 2021-06-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_merge_20210630_1347'),
        ('home', '0025_auto_20210630_0626'),
    ]

    operations = [
    ]
