# Generated by Django 3.1.14 on 2021-12-24 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_v1pageurltov2pagemap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CacheSettings',
        ),
    ]
