# Generated by Django 3.1.12 on 2021-06-30 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_homepage_new_featured_content'),
        ('home', '0034_merge_20210630_1703'),
    ]

    operations = [
    ]
