# Generated by Django 3.1.13 on 2021-12-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_delete_cachesettings'),
        ('home', '0035_auto_20211221_0822'),
    ]

    operations = [
    ]
