# Generated by Django 3.1.14 on 2021-12-27 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0036_merge_20211226_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocaleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='When active locale will be shown in the language selector')),
                ('is_main_language', models.BooleanField(default=False, help_text='When active locale will be used as default language for the site')),
                ('locale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locale_detail', to='wagtailcore.locale')),
            ],
        ),
    ]
