# Generated by Django 3.1.12 on 2021-07-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20210630_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='color',
        ),
        migrations.AddField(
            model_name='section',
            name='background_color',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='font_color',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
