# Generated by Django 3.1.13 on 2021-07-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20210630_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iogtflatmenuitem',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='section',
            name='icon',
        ),
    ]
