# Generated by Django 3.1.12 on 2021-06-30 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_merge_20210624_1250'),
        ('home', '0036_auto_20210630_1747'),
    ]

    operations = [
    ]
