# Generated by Django 3.1.13 on 2021-07-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20210701_1248'),
        ('home', '0037_merge_20210630_1847'),
        ('home', '0038_auto_20210701_1235'),
        ('home', '0037_auto_20210701_1604'),
    ]

    operations = [
    ]
