# Generated by Django 3.1.14 on 2022-01-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20220106_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='iogtflatmenuitem',
            name='display_only_in_single_column_view',
            field=models.BooleanField(default=False),
        ),
    ]
