# Generated by Django 3.1.14 on 2022-01-21 13:37
from pathlib import Path

from django.conf import settings
from django.core.files import File
from django.db import migrations


def _create_single_column_flat_menu_item(apps, schema_editor):
    Locale = apps.get_model('wagtailcore.Locale')
    Site = apps.get_model('wagtailcore.Site')
    FlatMenu = apps.get_model('wagtailmenus.FlatMenu')
    IogtFlatMenuItem = apps.get_model('home.IogtFlatMenuItem')
    Svg = apps.get_model('wagtailsvg.Svg')

    site = Site.objects.get(is_default_site=True)
    locales = Locale.objects.all()
    file = File(open(Path(settings.BASE_DIR) / 'iogt/static/icons/burger.svg'), name='burger.svg')
    icon = Svg.objects.create(title='burger', file=file)
    for locale in locales:
        menu, __ = FlatMenu.objects.get_or_create(handle=f'{locale.language_code}_menu_live', defaults={
            'title': f'{locale.language_code} main menu',
            'site': site,
            'heading': 'Main Menu',
        })
        IogtFlatMenuItem.objects.get_or_create(link_url='#menu', menu=menu, defaults={
            'link_text': 'Menu',
            'icon': icon,
            'display_only_in_single_column_view': True,
        })


def _remove_single_column_flat_menu_item(apps, schema_editor):
    Locale = apps.get_model('wagtailcore.Locale')
    FlatMenu = apps.get_model('wagtailmenus.FlatMenu')
    IogtFlatMenuItem = apps.get_model('home.IogtFlatMenuItem')

    locales = Locale.objects.all()
    for locale in locales:
        menu = FlatMenu.objects.filter(handle=f'{locale.language_code}_menu_live').first()
        if menu:
            menu_item = IogtFlatMenuItem.objects.filter(link_url='#menu', menu=menu).first()
            if menu_item:
                menu_item.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_iogtflatmenuitem_display_only_in_single_column_view'),
    ]

    operations = [
        migrations.RunPython(_create_single_column_flat_menu_item, _remove_single_column_flat_menu_item)
    ]
