# Generated by Django 3.1.14 on 2022-01-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('iogt_users', '0005_auto_20220120_0813'),
        ('questionnaires', '0026_auto_20220125_1149'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0040_auto_20220125_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterPage',
        ),
    ]
