# Generated by Django 3.1.14 on 2022-01-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20220125_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerpage',
            name='align_center',
        ),
        migrations.RemoveField(
            model_name='bannerpage',
            name='banner_background_image',
        ),
        migrations.RemoveField(
            model_name='bannerpage',
            name='banner_button_text',
        ),
        migrations.RemoveField(
            model_name='bannerpage',
            name='banner_description',
        ),
        migrations.RemoveField(
            model_name='bannerpage',
            name='banner_icon_button',
        ),
    ]
