# Generated by Django 3.1.13 on 2021-07-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20210706_1031'),
        ('home', '0040_auto_20210705_0909'),
    ]

    operations = [
    ]
