# Generated by Django 3.1.14 on 2022-02-08 11:53

from django.db import migrations
import home.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20220127_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='home_featured_content',
            field=wagtail.fields.StreamField([('page_button', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock()), ('text', wagtail.blocks.CharBlock(max_length=255, required=False))])), ('embedded_poll', wagtail.blocks.StructBlock([('direct_display', wagtail.blocks.BooleanBlock(required=False)), ('poll', home.blocks.EmbeddedQuestionnaireChooserBlock(page_type=['questionnaires.Poll']))])), ('embedded_survey', wagtail.blocks.StructBlock([('direct_display', wagtail.blocks.BooleanBlock(required=False)), ('survey', home.blocks.EmbeddedQuestionnaireChooserBlock(page_type=['questionnaires.Survey']))])), ('embedded_quiz', wagtail.blocks.StructBlock([('direct_display', wagtail.blocks.BooleanBlock(required=False)), ('quiz', home.blocks.EmbeddedQuestionnaireChooserBlock(page_type=['questionnaires.Quiz']))])), ('article', wagtail.blocks.StructBlock([('display_section_title', wagtail.blocks.BooleanBlock(required=False)), ('article', wagtail.blocks.PageChooserBlock(page_type=['home.Article']))]))], blank=True, null=True),
        ),
    ]
