# Generated by Django 3.1.14 on 2022-01-25 11:28
import re

from django.db import migrations


def _fix_article_paragraph_image_format(apps, schema_editor):
    Article = apps.get_model('home', 'Article')
    format_regex = re.compile('format="(left|right)"')
    articles = Article.objects.all()
    for article in articles:
        for block in article.body.stream_data:
            if block.get('type') == 'paragraph':
                block['value'] = format_regex.sub('format="fullwidth"', block.get('value'))

    Article.objects.bulk_update(articles, fields=['body'], batch_size=100)


def _fix_offline_app_paragraph_image_format(apps, schema_editor):
    OfflineAppPage = apps.get_model('home', 'OfflineAppPage')
    format_regex = re.compile('format="(left|right)"')
    offline_app_pages = OfflineAppPage.objects.all()
    for offline_app_page in offline_app_pages:
        for block in offline_app_page.body.stream_data:
            if block.get('type') == 'paragraph':
                block['value'] = format_regex.sub('format="fullwidth"', block.get('value'))

    OfflineAppPage.objects.bulk_update(offline_app_pages, fields=['body'], batch_size=100)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20220125_1128'),
    ]

    operations = [
        migrations.RunPython(_fix_article_paragraph_image_format, migrations.RunPython.noop),
        migrations.RunPython(_fix_offline_app_paragraph_image_format, migrations.RunPython.noop),
    ]
