# Generated by Django 3.1.13 on 2022-02-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20220208_1153'),
        ('home', '0042_auto_20220131_1453'),
    ]

    operations = [
    ]
