# Generated by Django 3.1.14 on 2022-02-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_merge_20220209_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v1pageurltov2pagemap',
            name='v1_page_url',
            field=models.TextField(),
        ),
    ]
