# Generated by Django 3.1.14 on 2022-03-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20220223_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svgtopngmap',
            name='fill_color',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='svgtopngmap',
            name='stroke_color',
            field=models.TextField(default=''),
        ),
    ]
