# Generated by Django 3.1.14 on 2022-03-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20220223_0819'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='svgtopngmap',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='svgtopngmap',
            constraint=models.UniqueConstraint(fields=('svg_path', 'fill_color', 'stroke_color'), name='unique_path_fill_stroke'),
        ),
        migrations.AddConstraint(
            model_name='svgtopngmap',
            constraint=models.UniqueConstraint(condition=models.Q(stroke_color=None), fields=('svg_path', 'fill_color'), name='unique_without_stroke'),
        ),
        migrations.AddConstraint(
            model_name='svgtopngmap',
            constraint=models.UniqueConstraint(condition=models.Q(fill_color=None), fields=('svg_path', 'stroke_color'), name='unique_without_fill'),
        ),
        migrations.AddConstraint(
            model_name='svgtopngmap',
            constraint=models.UniqueConstraint(condition=models.Q(('fill_color', None), ('stroke_color', None)), fields=('svg_path',), name='unique_without_fill_stroke'),
        ),
    ]
