# Generated by Django 3.1.14 on 2022-11-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20221018_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_image_resize_rule_width',
            field=models.IntegerField(choices=[(360, 'Default - Images resized to maximum width of 360px, a balance for smartphone and featurephone screen sizes (width-360)'), (430, 'Larger - Images resized to maximum width of 430px, designed for most smartphones (width-430)'), (533, 'Larger - Images resized to maximum width of 533px, experimental (width-533)'), (800, 'Larger - Images resized to maximum width of 800px, experimental (width-800)'), (1080, 'Larger - Images resized to maximum width of 1080px, experimental (width-1080)'), (1600, 'Larger - Images resized to maximum width of 1600px, experimental (width-1600)')], default=360),
        ),
    ]
