# Generated by Django 3.1.14 on 2022-10-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20221018_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themesettings',
            old_name='navbar_font_color',
            new_name='flat_menus_navbar_font_color',
        ),
    ]
