# Generated by Django 3.1.14 on 2022-11-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20221018_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maximum_width',
            field=models.IntegerField(choices=[(360, '360px'), (800, '800px')], default=360),
        ),
    ]
