# Generated by Django 3.1.14 on 2022-11-14 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0049_auto_20221018_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelinkpage',
            name='override_the_lead_image_from_the_destination_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='pagelinkpage',
            name='override_the_page_title_from_the_destination_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
