# Generated by Django 3.1.14 on 2022-12-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20221018_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='image_maximum_width',
            field=models.IntegerField(choices=[(360, 'Default - Images resized to maximum width of 360px, a balance for smartphone and featurephone screen sizes (width-360)'), (430, 'Larger - Images resized to maximum width of 430px, designed for most smartphones (width-430)'), (533, 'Larger - Images resized to maximum width of 533px, experimental (width-533)'), (800, 'Larger - Images resized to maximum width of 800px, experimental (width-800)'), (1080, 'Larger - Images resized to maximum width of 1080px, experimental (width-1080)'), (1600, 'Larger - Images resized to maximum width of 1600px, experimental (width-1600)')], default=360, help_text="\n        When you upload large images, IoGT resizes the original images to smaller pixel dimensions to reduce file size. \n        This results in less network usage and less space used on a device when content is downloaded for offline viewing. \n        By default, IoGT resizes images to 360px width maximum. This is a balanced image size for feature and smart phones \n        while keeping file size low, but also reduces image quality. If your users have affordable or free internet access,\n        you might consider increasing the resize width so images look better on computers. If you have an zero-rating agreement \n        with an MNO you should consider what impact increasing the file size of your images will have. More information is available in the \n        <a href='https://cms-manual.iogt.site/en/sections/setting-up-your-iogt-platform/customizing-iogt-to-your-context/image-resize-width/', target='_blank'> \n            IoGT CMS Manual\n        </a>.\n        "),
        ),
    ]
