# Generated by Django 3.1.14 on 2022-10-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20221018_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelinkpage',
            name='Override_the_Page_title_from_the_destination_Page',
            field=models.BooleanField(default=False),
        ),
    ]
