# Generated by Django 3.1.14 on 2022-11-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20221018_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maximum_width_of_image',
            field=models.IntegerField(default=360),
        ),
    ]
