# Generated by Django 3.1.14 on 2022-11-14 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0049_auto_20221018_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelinkpage',
            name='override_lead_image',
            field=models.ForeignKey(blank=True, help_text='Override the lead image from the destination page', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='pagelinkpage',
            name='override_title',
            field=models.CharField(blank=True, help_text='Override the page title from the destination page', max_length=255, null=True),
        ),
    ]
