# Generated by Django 3.2.19 on 2023-06-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20230330_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themesettings',
            old_name='navbar_background_color',
            new_name='flat_menu_background_color',
        ),
        migrations.RenameField(
            model_name='themesettings',
            old_name='navbar_font_color',
            new_name='flat_menu_font_color',
        ),
    ]
