# Generated by Django 3.2.20 on 2023-11-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0051_auto_20230330_1105"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="mtm_container_id",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Currently this feature only works on devices using JavaScript"
                    " (e.g. basic featurephones are not supported), and does not work"
                    " with MNO zero-rating or Meta Free Basics."
                ),
                max_length=255,
                null=True,
                verbose_name="Matomo Tag Manager container ID",
            ),
        ),
    ]
