# Generated by Django 3.2.23 on 2023-11-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0052_sitesettings_mtm_container_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="mtm_container_id",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Currently this feature only works on devices using JavaScript"
                    " (e.g. basic feature phones are not supported), and does not work"
                    " with MNO zero-rating or Meta Free Basics."
                ),
                max_length=255,
                null=True,
                verbose_name="Matomo Tag Manager container ID",
            ),
        ),
    ]
