# Generated by Django 3.2.23 on 2024-02-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_crankyuncle'),
    ]

    operations = [
        migrations.AddField(
            model_name='crankyuncle',
            name='commenting_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crankyuncle',
            name='commenting_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crankyuncle',
            name='commenting_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('disabled', 'Disabled'), ('timestamped', 'Timestamped'), ('inherited', 'Inherited')], default='inherited', max_length=15),
        ),
    ]
