# Generated by Django 3.2.25 on 2025-02-27 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0056_articlefeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_feedback', models.BooleanField(default=True, verbose_name='Enable Feedback')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Rating Settings',
            },
        ),
    ]
