# Generated by Django 3.2.25 on 2025-03-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_feedbacksettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='average_rating',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='number_of_reviews',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
