# Generated by Django 3.2.25 on 2025-07-28 12:22

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_notifications', '0003_auto_20250728_1222'),
        ('home', '0060_auto_20250703_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='notification_tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='user_notifications.NotificationTag'),
        ),
    ]
