# Generated by Django 5.2.4 on 2025-09-17 11:27

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_article_notification_tags'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('markdown', 2), ('paragraph_v1_legacy', 3), ('image', 4), ('list', 5), ('numbered_list', 6), ('page_button', 9), ('embedded_poll', 12), ('embedded_survey', 14), ('embedded_quiz', 16), ('media', 17), ('chat_bot', 20), ('download', 25)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image']}), 2: ('wagtailmarkdown.blocks.MarkdownBlock', (), {'icon': 'code'}), 3: ('home.blocks.RawHTMLBlock', (), {'icon': 'code'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.ListBlock', (2,), {}), 6: ('home.blocks.NumberedListBlock', (2,), {}), 7: ('wagtail.blocks.PageChooserBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('page', 7), ('text', 8)]], {}), 10: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 11: ('home.blocks.EmbeddedQuestionnaireChooserBlock', (), {'page_type': ['questionnaires.Poll']}), 12: ('wagtail.blocks.StructBlock', [[('direct_display', 10), ('poll', 11)]], {}), 13: ('home.blocks.EmbeddedQuestionnaireChooserBlock', (), {'page_type': ['questionnaires.Survey']}), 14: ('wagtail.blocks.StructBlock', [[('direct_display', 10), ('survey', 13)]], {}), 15: ('home.blocks.EmbeddedQuestionnaireChooserBlock', (), {'page_type': ['questionnaires.Quiz']}), 16: ('wagtail.blocks.StructBlock', [[('direct_display', 10), ('quiz', 15)]], {}), 17: ('home.blocks.MediaBlock', (), {'icon': 'media'}), 18: ('wagtail.blocks.CharBlock', (), {}), 19: ('messaging.blocks.ChatBotChannelChooserBlock', (), {}), 20: ('wagtail.blocks.StructBlock', [[('subject', 18), ('button_text', 18), ('trigger_string', 18), ('channel', 19)]], {}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'This text appears when it is possible for the user to install the app on their phone.'}), 22: ('wagtail.blocks.CharBlock', (), {'form_classname': 'red-help-text', 'help_text': 'This text appears when the user is using a feature phone and thus cannot install the app (the button will be disabled in this case). [Currently not implemented]', 'required': False}), 23: ('wagtail.blocks.CharBlock', (), {'help_text': "This text appears when the user is navigating the site via the offline app and thus it doesn't make sense to install the offline app again (the button will be disabled in this case).", 'required': False}), 24: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['wagtailcore.Page']}), 25: ('wagtail.blocks.StructBlock', [[('available_text', 21), ('unavailable_text', 22), ('offline_text', 23), ('page', 24), ('description', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='articletaggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
        migrations.AlterField(
            model_name='offlinecontentindexpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('markdown', 2), ('paragraph_v1_legacy', 3), ('image', 4), ('list', 5), ('numbered_list', 6), ('page_button', 9), ('embedded_poll', 12), ('embedded_survey', 14), ('embedded_quiz', 16), ('media', 17), ('chat_bot', 20), ('download', 25)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image']}), 2: ('wagtailmarkdown.blocks.MarkdownBlock', (), {'icon': 'code'}), 3: ('home.blocks.RawHTMLBlock', (), {'icon': 'code'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.ListBlock', (2,), {}), 6: ('home.blocks.NumberedListBlock', (2,), {}), 7: ('wagtail.blocks.PageChooserBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('page', 7), ('text', 8)]], {}), 10: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 11: ('home.blocks.EmbeddedQuestionnaireChooserBlock', (), {'page_type': ['questionnaires.Poll']}), 12: ('wagtail.blocks.StructBlock', [[('direct_display', 10), ('poll', 11)]], {}), 13: ('home.blocks.EmbeddedQuestionnaireChooserBlock', (), {'page_type': ['questionnaires.Survey']}), 14: ('wagtail.blocks.StructBlock', [[('direct_display', 10), ('survey', 13)]], {}), 15: ('home.blocks.EmbeddedQuestionnaireChooserBlock', (), {'page_type': ['questionnaires.Quiz']}), 16: ('wagtail.blocks.StructBlock', [[('direct_display', 10), ('quiz', 15)]], {}), 17: ('home.blocks.MediaBlock', (), {'icon': 'media'}), 18: ('wagtail.blocks.CharBlock', (), {}), 19: ('messaging.blocks.ChatBotChannelChooserBlock', (), {}), 20: ('wagtail.blocks.StructBlock', [[('subject', 18), ('button_text', 18), ('trigger_string', 18), ('channel', 19)]], {}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'This text appears when it is possible for the user to install the app on their phone.'}), 22: ('wagtail.blocks.CharBlock', (), {'form_classname': 'red-help-text', 'help_text': 'This text appears when the user is using a feature phone and thus cannot install the app (the button will be disabled in this case). [Currently not implemented]', 'required': False}), 23: ('wagtail.blocks.CharBlock', (), {'help_text': "This text appears when the user is navigating the site via the offline app and thus it doesn't make sense to install the offline app again (the button will be disabled in this case).", 'required': False}), 24: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['wagtailcore.Page']}), 25: ('wagtail.blocks.StructBlock', [[('available_text', 21), ('unavailable_text', 22), ('offline_text', 23), ('page', 24), ('description', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='sectiontaggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
    ]
