# Generated by Django 5.2.4 on 2025-09-04 06:06

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_alter_manifestsettings_language'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('user_notifications', '0005_seed_notification_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='notification_tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='user_notifications.notificationtag'),
        ),
        migrations.AlterField(
            model_name='articletaggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
        migrations.AlterField(
            model_name='sectiontaggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
    ]
