# Generated by Django 3.1.12 on 2021-06-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30)),
                ('display_name', models.CharField(max_length=80)),
                ('request_url', models.URLField()),
            ],
        ),
    ]
