# Generated by Django 3.1.12 on 2021-06-13 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_chatbotchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='quick_replies',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='message',
            name='rapid_pro_message_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sent_from_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='chatbot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='messaging.chatbotchannel'),
            preserve_default=False,
        ),
    ]
