# Generated by Django 3.1.12 on 2021-06-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20210613_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='rapid_pro_message_id',
            field=models.IntegerField(null=True),
        ),
    ]
