# Generated by Django 3.1.12 on 2021-06-15 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0004_auto_20210613_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='thread',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
