# Generated by Django 3.2.25 on 2025-03-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_auto_20230315_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_chatbot_message',
            field=models.BooleanField(default=False),
        ),
    ]
