# Generated by Django 5.2.4 on 2025-12-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_message_is_chatbot_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rapidpro_message_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
