# Generated by Django 3.1.12 on 2021-06-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_remove_message_sent_from_bot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='rapid_pro_message_id',
            new_name='rapidpro_message_id',
        ),
        migrations.AlterField(
            model_name='message',
            name='attachments',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='message',
            name='quick_replies',
            field=models.JSONField(default=list),
        ),
    ]
