# Generated by Django 3.2.25 on 2025-07-28 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.NOTIFICATIONS_NOTIFICATION_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_notifications', '0002_notificationpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='usernotificationtemplate',
            name='type',
            field=models.CharField(choices=[('signup', 'User Signup'), ('article', 'Article Published'), ('survey', 'Survey Published')], default='User Signup', help_text='Select the type of notification this template is used for.', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NotificationMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_clicked', models.BooleanField(default=False)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to=settings.NOTIFICATIONS_NOTIFICATION_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_key', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='content_tags',
            field=models.ManyToManyField(blank=True, to='user_notifications.NotificationTag'),
        ),
    ]
