# Generated by Django 3.2.25 on 2025-07-31 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.NOTIFICATIONS_NOTIFICATION_MODEL),
        ('user_notifications', '0003_auto_20250728_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='notification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.NOTIFICATIONS_NOTIFICATION_MODEL),
        ),
    ]
