# Generated by Django 3.2.25 on 2025-07-31 06:02

from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.models import Group
from iogt_users.models import User
import django.db.models.deletion
from user_notifications.models import UserNotificationTemplate


def reverse_seed_notification_tables(apps, schema_editor):
    Group.objects.filter(name="Notify All Users").delete()
    UserNotificationTemplate.objects.all().delete()


def seed_notification_tables(apps, schema_editor):
    group, created = Group.objects.get_or_create(name="Notify All Users")
    all_users = User.objects.all()
    group.user_set.set(all_users)  # replaces current users with all users

    article_template, _ = UserNotificationTemplate.objects.get_or_create(
        type='article',
        title='A New Article Has Been Published!',
        message='Tap here to read the latest article now.'
    )

    survey_template, _ = UserNotificationTemplate.objects.get_or_create(
        type='survey',
        title='We Value Your Feedback!',
        message='Take a quick survey to share your thoughts.'
    )
    section_template, _ = UserNotificationTemplate.objects.get_or_create(
        type='section',
        title='We Value Your Feedback!',
        message='Tap here to see what this section is all about'
    )

    signup_template, _ = UserNotificationTemplate.objects.get_or_create(
        type='signup',
        title='Welcome Aboard!',
        message='Your account has been successfully created.'
    )



class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.NOTIFICATIONS_NOTIFICATION_MODEL),
        ('user_notifications', '0004_notificationlog_notification'),
        ('iogt_users', '0006_user_interactive_uuid'),
    ]

    operations = [
        migrations.RunPython(seed_notification_tables, reverse_seed_notification_tables),
    ]
