# Generated by Django 5.2.4 on 2025-09-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_notifications', '0005_seed_notification_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationtemplate',
            name='type',
            field=models.CharField(choices=[('signup', 'User Signup'), ('article', 'Article Published'), ('survey', 'Survey Published'), ('section', 'Section Published')], help_text='Select the type of notification this template is used for.', max_length=20, unique=True),
        ),
    ]
