# Generated by Django 3.1.11 on 2021-05-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveypage',
            old_name='intro',
            new_name='survey_question',
        ),
    ]
